import { Drug } from "./types";
import extraDrugs from "@/data/drugs.json";

// Exam-focused seed data. Points are intentionally short for quick revision.
// Not medical advice — for study only.
const CORE_DRUGS: Drug[] = [
  // ─────────────────────────── AUTONOMIC NERVOUS SYSTEM ───────────────────────────
  {
    id: "atropine",
    name: "Atropine",
    topic: "autonomic-nervous-system",
    drugClass: "Muscarinic (anticholinergic) antagonist",
    moa: "Competitively blocks muscarinic (M) acetylcholine receptors.",
    uses: ["Bradycardia", "Organophosphate poisoning", "Preanesthetic (dries secretions)", "Mydriatic / cycloplegic"],
    sideEffects: ["Dry mouth", "Blurred vision", "Tachycardia", "Urinary retention", "Constipation", "Hyperthermia"],
    contraindications: ["Glaucoma (narrow-angle)", "Benign prostatic hyperplasia", "Paralytic ileus"],
    interactions: ["Additive antimuscarinic effect with antihistamines, TCAs, phenothiazines"],
    mnemonic: "\"Dry as a bone, blind as a bat, red as a beet, mad as a hatter, hot as a hare.\"",
    vivaQuestions: [
      { q: "Antidote of atropine poisoning?", a: "Physostigmine (crosses BBB)." },
      { q: "Why is atropine used in organophosphate poisoning?", a: "It blocks muscarinic overstimulation caused by acetylcholine accumulation." },
    ],
    mcqs: [
      {
        id: "atropine-m1",
        question: "Atropine acts by:",
        options: ["Blocking nicotinic receptors", "Blocking muscarinic receptors", "Stimulating muscarinic receptors", "Inhibiting acetylcholinesterase"],
        answerIndex: 1,
        explanation: "Atropine is a competitive muscarinic antagonist.",
      },
      {
        id: "atropine-m2",
        question: "Atropine is contraindicated in:",
        options: ["Bradycardia", "Narrow-angle glaucoma", "Organophosphate poisoning", "Preanesthetic medication"],
        answerIndex: 1,
        explanation: "It causes mydriasis, raising intraocular pressure — dangerous in narrow-angle glaucoma.",
      },
    ],
  },
  {
    id: "adrenaline",
    name: "Adrenaline (Epinephrine)",
    topic: "autonomic-nervous-system",
    drugClass: "Non-selective adrenergic agonist (α1, α2, β1, β2)",
    moa: "Stimulates all adrenergic receptors — vasoconstriction (α1), ↑ heart rate/force (β1), bronchodilation (β2).",
    uses: ["Anaphylaxis (drug of choice)", "Cardiac arrest", "With local anesthetics (prolongs action)", "Acute severe asthma"],
    sideEffects: ["Palpitations", "Hypertension", "Anxiety / tremor", "Arrhythmias", "Headache"],
    contraindications: ["Not absolute in emergencies; caution in hyperthyroidism, ischemic heart disease"],
    interactions: ["Non-selective β-blockers → unopposed α → severe hypertension", "MAO inhibitors potentiate effect"],
    mnemonic: "\"A for Anaphylaxis — Adrenaline first.\"",
    vivaQuestions: [
      { q: "Drug of choice for anaphylactic shock?", a: "Adrenaline (IM, 0.5 mg of 1:1000)." },
      { q: "Why add adrenaline to lignocaine?", a: "Vasoconstriction reduces systemic absorption, prolonging anesthesia and reducing bleeding." },
    ],
    mcqs: [
      {
        id: "adr-m1",
        question: "Drug of choice in anaphylaxis:",
        options: ["Hydrocortisone", "Adrenaline", "Diphenhydramine", "Atropine"],
        answerIndex: 1,
        explanation: "Adrenaline reverses bronchospasm and hypotension immediately.",
      },
      {
        id: "adr-m2",
        question: "Adrenaline with a non-selective beta-blocker can cause:",
        options: ["Hypotension", "Unopposed alpha → hypertension", "Bradycardia only", "No interaction"],
        answerIndex: 1,
        explanation: "Blocked β2 vasodilation leaves α1 vasoconstriction unopposed → hypertensive crisis.",
      },
    ],
  },
  {
    id: "neostigmine",
    name: "Neostigmine",
    topic: "autonomic-nervous-system",
    drugClass: "Reversible acetylcholinesterase inhibitor",
    moa: "Inhibits acetylcholinesterase → ↑ acetylcholine at synapses (does not cross BBB).",
    uses: ["Myasthenia gravis", "Reversal of non-depolarizing neuromuscular blockers", "Postoperative paralytic ileus / urinary retention"],
    sideEffects: ["Bradycardia", "Salivation", "Diarrhea", "Muscle cramps", "Bronchoconstriction"],
    contraindications: ["Mechanical intestinal/urinary obstruction", "Bronchial asthma"],
    interactions: ["Given with atropine/glycopyrrolate to block muscarinic effects during NM block reversal"],
    mnemonic: "\"Neo does not go — no CNS entry (quaternary amine).\"",
    vivaQuestions: [
      { q: "Difference between neostigmine and physostigmine?", a: "Physostigmine (tertiary amine) crosses BBB; neostigmine (quaternary) does not." },
      { q: "Test for myasthenia gravis?", a: "Edrophonium (Tensilon) test — short-acting AChE inhibitor." },
    ],
    mcqs: [
      {
        id: "neo-m1",
        question: "Neostigmine is used in all EXCEPT:",
        options: ["Myasthenia gravis", "Reversal of tubocurarine", "Glaucoma requiring CNS action", "Postoperative ileus"],
        answerIndex: 2,
        explanation: "Neostigmine does not cross the blood-brain barrier, so it lacks CNS action.",
      },
      {
        id: "neo-m2",
        question: "Neostigmine inhibits:",
        options: ["Monoamine oxidase", "Acetylcholinesterase", "COMT", "Choline acetyltransferase"],
        answerIndex: 1,
        explanation: "It reversibly inhibits acetylcholinesterase.",
      },
    ],
  },
  {
    id: "propranolol",
    name: "Propranolol",
    topic: "autonomic-nervous-system",
    drugClass: "Non-selective beta (β1 & β2) blocker",
    moa: "Blocks β1 (heart) and β2 (bronchi, vessels) adrenergic receptors.",
    uses: ["Hypertension", "Angina", "Migraine prophylaxis", "Thyrotoxicosis", "Essential tremor", "Performance anxiety"],
    sideEffects: ["Bradycardia", "Bronchospasm", "Fatigue", "Cold extremities", "Masks hypoglycemia symptoms"],
    contraindications: ["Bronchial asthma / COPD", "Heart block", "Decompensated heart failure"],
    interactions: ["Verapamil → severe bradycardia / AV block", "Masks & prolongs insulin-induced hypoglycemia"],
    mnemonic: "\"Propranolol — Pro blocks Pair of betas (β1+β2).\"",
    vivaQuestions: [
      { q: "Why avoid non-selective β-blockers in asthma?", a: "β2 blockade causes bronchoconstriction." },
      { q: "Use of propranolol in thyrotoxicosis?", a: "Controls sympathetic symptoms and inhibits peripheral T4→T3 conversion." },
    ],
    mcqs: [
      {
        id: "prop-m1",
        question: "Propranolol is contraindicated in:",
        options: ["Migraine", "Bronchial asthma", "Hypertension", "Essential tremor"],
        answerIndex: 1,
        explanation: "β2 blockade precipitates bronchospasm.",
      },
      {
        id: "prop-m2",
        question: "Propranolol is used for migraine:",
        options: ["Acute attack abortion", "Prophylaxis", "Both", "Neither"],
        answerIndex: 1,
        explanation: "β-blockers are used for migraine prophylaxis, not acute abortion.",
      },
    ],
  },
  // ─────────────────────────── CARDIOVASCULAR ───────────────────────────
  {
    id: "metoprolol",
    name: "Metoprolol",
    topic: "cardiovascular-drugs",
    drugClass: "Cardioselective β1 blocker",
    moa: "Selectively blocks β1 receptors in the heart → ↓ heart rate, ↓ contractility, ↓ renin.",
    uses: ["Hypertension", "Angina", "Chronic heart failure", "Post-MI", "Arrhythmias"],
    sideEffects: ["Bradycardia", "Fatigue", "Cold extremities", "Depression", "Masks hypoglycemia"],
    contraindications: ["Severe asthma", "Heart block (2nd/3rd degree)", "Decompensated heart failure"],
    interactions: ["Verapamil/diltiazem → bradycardia", "NSAIDs blunt antihypertensive effect"],
    mnemonic: "\"Meto = Heart Slow\" (β1 = 1 heart).",
    vivaQuestions: [
      { q: "Why is metoprolol preferred over propranolol in asthmatics?", a: "It is β1-selective, causing less bronchoconstriction." },
      { q: "Which β-blockers are used in heart failure?", a: "Metoprolol, bisoprolol, carvedilol, nebivolol." },
    ],
    mcqs: [
      {
        id: "meto-m1",
        question: "Metoprolol is a:",
        options: ["Non-selective β-blocker", "β1-selective blocker", "α-blocker", "β2 agonist"],
        answerIndex: 1,
        explanation: "Metoprolol is cardioselective (β1).",
      },
      {
        id: "meto-m2",
        question: "Beta-blocker proven to reduce mortality in heart failure:",
        options: ["Atenolol", "Metoprolol", "Sotalol", "Esmolol"],
        answerIndex: 1,
        explanation: "Metoprolol succinate is one of the evidence-based HF β-blockers.",
      },
    ],
  },
  {
    id: "losartan",
    name: "Losartan",
    topic: "cardiovascular-drugs",
    drugClass: "Angiotensin II receptor blocker (ARB)",
    moa: "Blocks angiotensin II AT1 receptors → vasodilation, ↓ aldosterone.",
    uses: ["Hypertension", "Diabetic nephropathy", "Heart failure (ACE-intolerant)"],
    sideEffects: ["Hyperkalemia", "Dizziness", "Hypotension", "Renal impairment"],
    contraindications: ["Pregnancy", "Bilateral renal artery stenosis", "Hyperkalemia"],
    interactions: ["K+-sparing diuretics → hyperkalemia", "NSAIDs → ↓ effect + renal injury"],
    mnemonic: "\"-sartan blocks the receptor; -pril blocks the enzyme.\"",
    vivaQuestions: [
      { q: "Why does losartan not cause cough like ACE inhibitors?", a: "It doesn't raise bradykinin, so no bradykinin-mediated dry cough." },
      { q: "Losartan in pregnancy?", a: "Contraindicated — fetal renal damage / oligohydramnios." },
    ],
    mcqs: [
      {
        id: "los-m1",
        question: "Losartan differs from enalapril in that it does NOT cause:",
        options: ["Hyperkalemia", "Dry cough", "Hypotension", "Renal impairment"],
        answerIndex: 1,
        explanation: "ARBs don't increase bradykinin, so cough is uncommon.",
      },
      {
        id: "los-m2",
        question: "Losartan is contraindicated in:",
        options: ["Diabetes", "Pregnancy", "Hypertension", "Heart failure"],
        answerIndex: 1,
        explanation: "ARBs are teratogenic (fetal renal toxicity).",
      },
    ],
  },
  {
    id: "amlodipine",
    name: "Amlodipine",
    topic: "cardiovascular-drugs",
    drugClass: "Dihydropyridine calcium channel blocker",
    moa: "Blocks L-type Ca²⁺ channels in vascular smooth muscle → arterial vasodilation.",
    uses: ["Hypertension", "Stable & Prinzmetal angina", "Raynaud's phenomenon"],
    sideEffects: ["Pedal (ankle) edema", "Flushing", "Headache", "Reflex tachycardia", "Gum hyperplasia"],
    contraindications: ["Severe aortic stenosis", "Cardiogenic shock"],
    interactions: ["Additive hypotension with other antihypertensives", "CYP3A4 inhibitors ↑ levels"],
    mnemonic: "\"Amlo → Ankle edema.\"",
    vivaQuestions: [
      { q: "Most common side effect of amlodipine?", a: "Pedal edema (from precapillary vasodilation)." },
      { q: "Difference between dihydropyridine and non-dihydropyridine CCBs?", a: "DHPs (amlodipine) act on vessels; non-DHPs (verapamil, diltiazem) act more on the heart." },
    ],
    mcqs: [
      {
        id: "aml-m1",
        question: "Characteristic side effect of amlodipine:",
        options: ["Dry cough", "Ankle edema", "Hyperkalemia", "Bradycardia"],
        answerIndex: 1,
        explanation: "Precapillary arteriolar dilation causes ankle/pedal edema.",
      },
      {
        id: "aml-m2",
        question: "Amlodipine primarily acts on:",
        options: ["Cardiac muscle", "Vascular smooth muscle", "SA node", "Skeletal muscle"],
        answerIndex: 1,
        explanation: "Dihydropyridines are vasoselective.",
      },
    ],
  },
  {
    id: "furosemide",
    name: "Furosemide",
    topic: "cardiovascular-drugs",
    drugClass: "Loop diuretic",
    moa: "Inhibits Na⁺/K⁺/2Cl⁻ cotransporter in the thick ascending limb of loop of Henle.",
    uses: ["Acute pulmonary edema", "Heart failure", "Edema (hepatic/renal)", "Hypertension with renal impairment", "Hyperkalemia"],
    sideEffects: ["Hypokalemia", "Hyponatremia", "Ototoxicity", "Hyperuricemia (gout)", "Hypocalcemia", "Dehydration"],
    contraindications: ["Severe hypokalemia", "Sulfa allergy (caution)", "Anuria"],
    interactions: ["Aminoglycosides → ↑ ototoxicity", "Digoxin toxicity via hypokalemia", "Lithium retention"],
    mnemonic: "\"Loops LOSE calcium\" (vs thiazides that keep it).",
    vivaQuestions: [
      { q: "Most efficacious diuretic?", a: "Loop diuretics (furosemide) — 'high-ceiling' diuretics." },
      { q: "Why monitor potassium with furosemide?", a: "It causes hypokalemia, which increases digoxin toxicity risk." },
    ],
    mcqs: [
      {
        id: "fur-m1",
        question: "Furosemide acts on:",
        options: ["Distal convoluted tubule", "Thick ascending limb of loop of Henle", "Collecting duct", "Proximal tubule"],
        answerIndex: 1,
        explanation: "It blocks the Na-K-2Cl cotransporter in the TAL.",
      },
      {
        id: "fur-m2",
        question: "Furosemide causes all EXCEPT:",
        options: ["Hypokalemia", "Ototoxicity", "Hypercalcemia", "Hyperuricemia"],
        answerIndex: 2,
        explanation: "Loop diuretics cause HYPOcalcemia (calcium is lost).",
      },
    ],
  },
  {
    id: "digoxin",
    name: "Digoxin",
    topic: "cardiovascular-drugs",
    drugClass: "Cardiac glycoside",
    moa: "Inhibits Na⁺/K⁺-ATPase → ↑ intracellular Ca²⁺ → positive inotropy; ↑ vagal tone → ↓ AV conduction.",
    uses: ["Heart failure (with reduced EF)", "Atrial fibrillation / flutter (rate control)"],
    sideEffects: ["Nausea/vomiting", "Yellow-green vision (xanthopsia)", "Arrhythmias", "Confusion", "Gynecomastia"],
    contraindications: ["Ventricular fibrillation", "WPW syndrome", "2nd/3rd degree heart block"],
    interactions: ["Hypokalemia (diuretics) ↑ toxicity", "Quinidine, verapamil, amiodarone ↑ digoxin levels"],
    mnemonic: "\"Digoxin — Dig sees yellow\" (xanthopsia). Narrow therapeutic index!",
    vivaQuestions: [
      { q: "Antidote for severe digoxin toxicity?", a: "Digoxin-specific antibody (Fab) fragments (Digibind)." },
      { q: "Which electrolyte imbalance worsens digoxin toxicity?", a: "Hypokalemia (and hypomagnesemia, hypercalcemia)." },
    ],
    mcqs: [
      {
        id: "dig-m1",
        question: "Digoxin inhibits:",
        options: ["Na⁺/K⁺-ATPase", "Ca²⁺ channels", "β receptors", "Phosphodiesterase"],
        answerIndex: 0,
        explanation: "Na/K-ATPase inhibition raises intracellular calcium.",
      },
      {
        id: "dig-m2",
        question: "Digoxin toxicity is precipitated by:",
        options: ["Hyperkalemia", "Hypokalemia", "Hypernatremia", "Hypercalcemia... no"],
        answerIndex: 1,
        explanation: "Hypokalemia increases digoxin binding to Na/K-ATPase, worsening toxicity.",
      },
    ],
  },
  // ─────────────────────────── CNS ───────────────────────────
  {
    id: "diazepam",
    name: "Diazepam",
    topic: "cns-drugs",
    drugClass: "Long-acting benzodiazepine",
    moa: "Enhances GABA-A action → ↑ frequency of Cl⁻ channel opening → CNS depression.",
    uses: ["Anxiety", "Status epilepticus", "Alcohol withdrawal", "Muscle spasm", "Preanesthetic sedation"],
    sideEffects: ["Sedation", "Drowsiness", "Dependence", "Respiratory depression (IV)", "Anterograde amnesia"],
    contraindications: ["Severe respiratory depression", "Myasthenia gravis", "Acute narrow-angle glaucoma"],
    interactions: ["Additive CNS depression with alcohol & opioids", "Cimetidine ↑ levels"],
    mnemonic: "\"Benzos ↑ Frequency; Barbs ↑ Duration\" of Cl⁻ channel opening.",
    vivaQuestions: [
      { q: "Antidote for benzodiazepine overdose?", a: "Flumazenil (competitive GABA-A antagonist)." },
      { q: "Drug of choice for status epilepticus?", a: "IV lorazepam or diazepam for acute control." },
    ],
    mcqs: [
      {
        id: "diaz-m1",
        question: "Benzodiazepines act by increasing:",
        options: ["Duration of Cl⁻ channel opening", "Frequency of Cl⁻ channel opening", "Na⁺ influx", "K⁺ efflux"],
        answerIndex: 1,
        explanation: "Benzodiazepines increase the frequency of GABA-A Cl⁻ channel opening.",
      },
      {
        id: "diaz-m2",
        question: "Flumazenil is used for:",
        options: ["Opioid overdose", "Benzodiazepine overdose", "Paracetamol overdose", "Digoxin toxicity"],
        answerIndex: 1,
        explanation: "Flumazenil is the specific benzodiazepine antagonist.",
      },
    ],
  },
  {
    id: "morphine",
    name: "Morphine",
    topic: "cns-drugs",
    drugClass: "Opioid agonist (μ receptor)",
    moa: "Agonist at μ opioid receptors → ↓ pain transmission, ↑ pain threshold.",
    uses: ["Severe pain (MI, cancer, trauma)", "Acute pulmonary edema", "Preanesthetic medication"],
    sideEffects: ["Respiratory depression", "Constipation", "Miosis (pinpoint pupils)", "Nausea", "Dependence", "Hypotension"],
    contraindications: ["Head injury (↑ intracranial pressure)", "Bronchial asthma", "Respiratory failure"],
    interactions: ["Additive CNS/respiratory depression with sedatives & alcohol"],
    mnemonic: "\"Morphine → Miosis + Muscle (smooth) constipation.\"",
    vivaQuestions: [
      { q: "Antidote for opioid overdose?", a: "Naloxone (short-acting μ antagonist)." },
      { q: "Triad of opioid overdose?", a: "Coma, pinpoint pupils, respiratory depression." },
    ],
    mcqs: [
      {
        id: "mor-m1",
        question: "Pinpoint pupils are characteristic of:",
        options: ["Atropine poisoning", "Morphine poisoning", "Amphetamine", "Cocaine"],
        answerIndex: 1,
        explanation: "Morphine causes miosis via Edinger-Westphal nucleus stimulation.",
      },
      {
        id: "mor-m2",
        question: "Naloxone reverses morphine by:",
        options: ["Agonizing μ receptors", "Antagonizing opioid receptors", "Inhibiting COX", "Blocking GABA"],
        answerIndex: 1,
        explanation: "Naloxone is a competitive opioid receptor antagonist.",
      },
    ],
  },
  {
    id: "phenytoin",
    name: "Phenytoin",
    topic: "cns-drugs",
    drugClass: "Antiepileptic (hydantoin)",
    moa: "Blocks voltage-gated Na⁺ channels → stabilizes neuronal membranes, prolongs inactivation.",
    uses: ["Generalized tonic-clonic seizures", "Partial seizures", "Status epilepticus (2nd line)", "Trigeminal neuralgia"],
    sideEffects: ["Gingival hyperplasia", "Hirsutism", "Nystagmus/ataxia", "Megaloblastic anemia", "Teratogenic (fetal hydantoin syndrome)"],
    contraindications: ["Sinus bradycardia", "Heart block", "Pregnancy (caution)"],
    interactions: ["Potent CYP450 inducer → ↓ OCPs, warfarin", "Follows zero-order kinetics at high doses"],
    mnemonic: "\"Phenytoin → gums Puff up (gingival hyperplasia).\"",
    vivaQuestions: [
      { q: "What kinetics does phenytoin follow?", a: "Zero-order (saturation) kinetics at therapeutic doses — small dose ↑ = large plasma ↑." },
      { q: "Characteristic dental side effect?", a: "Gingival hyperplasia." },
    ],
    mcqs: [
      {
        id: "phen-m1",
        question: "Phenytoin acts by blocking:",
        options: ["Ca²⁺ channels", "Na⁺ channels", "GABA transaminase", "K⁺ channels"],
        answerIndex: 1,
        explanation: "It blocks voltage-gated sodium channels.",
      },
      {
        id: "phen-m2",
        question: "Gingival hyperplasia is caused by:",
        options: ["Valproate", "Phenytoin", "Carbamazepine", "Ethosuximide"],
        answerIndex: 1,
        explanation: "Gum hyperplasia is a classic phenytoin adverse effect.",
      },
    ],
  },
  {
    id: "fluoxetine",
    name: "Fluoxetine",
    topic: "cns-drugs",
    drugClass: "Selective serotonin reuptake inhibitor (SSRI)",
    moa: "Inhibits presynaptic serotonin (5-HT) reuptake → ↑ synaptic serotonin.",
    uses: ["Major depression", "OCD", "Panic disorder", "Bulimia nervosa", "PMDD"],
    sideEffects: ["Nausea", "Sexual dysfunction", "Insomnia", "Serotonin syndrome", "Initial ↑ anxiety"],
    contraindications: ["Concurrent MAO inhibitors", "Mania"],
    interactions: ["MAOIs → serotonin syndrome (fatal)", "CYP2D6 inhibitor → ↑ levels of other drugs"],
    mnemonic: "\"SSRIs are Safer in overdose than TCAs.\"",
    vivaQuestions: [
      { q: "Why are SSRIs preferred over TCAs?", a: "Fewer anticholinergic/cardiac effects and much safer in overdose." },
      { q: "What is serotonin syndrome?", a: "Hyperthermia, agitation, tremor, clonus, autonomic instability from excess serotonin." },
    ],
    mcqs: [
      {
        id: "flu-m1",
        question: "Fluoxetine is a:",
        options: ["TCA", "SSRI", "MAOI", "SNRI"],
        answerIndex: 1,
        explanation: "Fluoxetine selectively inhibits serotonin reuptake.",
      },
      {
        id: "flu-m2",
        question: "SSRI + MAOI can cause:",
        options: ["Hypertensive crisis only", "Serotonin syndrome", "Neuroleptic malignant syndrome", "No interaction"],
        answerIndex: 1,
        explanation: "The combination can precipitate life-threatening serotonin syndrome.",
      },
    ],
  },
  // ─────────────────────────── ANTIBIOTICS ───────────────────────────
  {
    id: "amoxicillin",
    name: "Amoxicillin",
    topic: "antibiotics",
    drugClass: "Aminopenicillin (β-lactam)",
    moa: "Inhibits bacterial cell wall synthesis by binding penicillin-binding proteins (transpeptidase).",
    uses: ["Respiratory tract infections", "Otitis media", "UTI", "H. pylori (triple therapy)", "Dental infections"],
    sideEffects: ["Rash", "Diarrhea", "Hypersensitivity/anaphylaxis", "Pseudomembranous colitis"],
    contraindications: ["Penicillin allergy", "Infectious mononucleosis (rash)"],
    interactions: ["Probenecid ↑ levels (↓ renal excretion)", "May ↓ OCP efficacy"],
    mnemonic: "\"-cillin = Cell wall inhibitor.\"",
    vivaQuestions: [
      { q: "Why combine amoxicillin with clavulanic acid?", a: "Clavulanic acid inhibits β-lactamase, extending the spectrum." },
      { q: "Mechanism of penicillin action?", a: "Inhibits transpeptidation of the bacterial cell wall (bactericidal)." },
    ],
    mcqs: [
      {
        id: "amox-m1",
        question: "Amoxicillin acts by inhibiting:",
        options: ["Protein synthesis", "Cell wall synthesis", "DNA gyrase", "Folate synthesis"],
        answerIndex: 1,
        explanation: "β-lactams inhibit cell wall synthesis via PBPs.",
      },
      {
        id: "amox-m2",
        question: "Clavulanic acid is added to amoxicillin to:",
        options: ["Increase absorption", "Inhibit β-lactamase", "Reduce allergy", "Prolong half-life"],
        answerIndex: 1,
        explanation: "Clavulanic acid is a β-lactamase inhibitor.",
      },
    ],
  },
  {
    id: "azithromycin",
    name: "Azithromycin",
    topic: "antibiotics",
    drugClass: "Macrolide",
    moa: "Binds 50S ribosomal subunit → inhibits bacterial protein synthesis (bacteriostatic).",
    uses: ["Atypical pneumonia", "Chlamydia", "Whooping cough", "Penicillin-allergic streptococcal infections"],
    sideEffects: ["GI upset", "QT prolongation", "Cholestatic hepatitis", "Reversible hearing loss"],
    contraindications: ["QT prolongation / arrhythmia risk", "Severe hepatic impairment"],
    interactions: ["QT-prolonging drugs → arrhythmia", "Macrolides inhibit CYP3A4 (azithro least of all)"],
    mnemonic: "\"Macrolides bind 50S (buy AT 30, CCEL at 50).\"",
    vivaQuestions: [
      { q: "Which ribosomal subunit do macrolides bind?", a: "The 50S subunit." },
      { q: "Advantage of azithromycin's long half-life?", a: "Once-daily, short-course dosing (e.g., 3–5 days)." },
    ],
    mcqs: [
      {
        id: "azi-m1",
        question: "Azithromycin binds to:",
        options: ["30S subunit", "50S subunit", "DNA gyrase", "RNA polymerase"],
        answerIndex: 1,
        explanation: "Macrolides bind the 50S ribosomal subunit.",
      },
      {
        id: "azi-m2",
        question: "A serious cardiac effect of azithromycin:",
        options: ["Bradycardia", "QT prolongation", "Hypertension", "Heart block"],
        answerIndex: 1,
        explanation: "Macrolides can prolong the QT interval.",
      },
    ],
  },
  {
    id: "ciprofloxacin",
    name: "Ciprofloxacin",
    topic: "antibiotics",
    drugClass: "Fluoroquinolone",
    moa: "Inhibits DNA gyrase (topoisomerase II) and topoisomerase IV → blocks DNA replication.",
    uses: ["UTI", "Typhoid fever", "GI infections", "Pseudomonas infections", "Anthrax prophylaxis"],
    sideEffects: ["Tendon rupture (Achilles)", "QT prolongation", "Photosensitivity", "GI upset", "CNS effects/seizures"],
    contraindications: ["Children/adolescents (cartilage damage)", "Pregnancy & lactation", "Myasthenia gravis"],
    interactions: ["Antacids/iron/calcium ↓ absorption (chelation)", "↑ theophylline & warfarin levels"],
    mnemonic: "\"Fluoroquinolones hurt attachments — Tendons & cartilage.\"",
    vivaQuestions: [
      { q: "Why are fluoroquinolones avoided in children?", a: "Risk of cartilage/tendon damage (arthropathy)." },
      { q: "Enzyme target of ciprofloxacin?", a: "DNA gyrase (topoisomerase II) in gram-negatives." },
    ],
    mcqs: [
      {
        id: "cip-m1",
        question: "Ciprofloxacin inhibits:",
        options: ["Cell wall synthesis", "DNA gyrase", "50S subunit", "Folate synthesis"],
        answerIndex: 1,
        explanation: "Fluoroquinolones inhibit DNA gyrase and topoisomerase IV.",
      },
      {
        id: "cip-m2",
        question: "Ciprofloxacin absorption is reduced by:",
        options: ["Vitamin C", "Antacids containing calcium/magnesium", "Fatty meals", "Beta-blockers"],
        answerIndex: 1,
        explanation: "Divalent/trivalent cations chelate fluoroquinolones.",
      },
    ],
  },
  {
    id: "gentamicin",
    name: "Gentamicin",
    topic: "antibiotics",
    drugClass: "Aminoglycoside",
    moa: "Binds 30S ribosomal subunit → misreading of mRNA → inhibits protein synthesis (bactericidal).",
    uses: ["Serious gram-negative infections", "Septicemia", "Synergy with β-lactams for endocarditis"],
    sideEffects: ["Nephrotoxicity", "Ototoxicity (irreversible)", "Neuromuscular blockade"],
    contraindications: ["Myasthenia gravis", "Pregnancy", "Pre-existing renal/hearing impairment"],
    interactions: ["Loop diuretics → ↑ ototoxicity", "Other nephrotoxins (vancomycin) → ↑ renal injury"],
    mnemonic: "\"Aminoglycosides = Nephro + Oto toxicity (Mean GENTS damage kidneys & ears).\"",
    vivaQuestions: [
      { q: "Two main toxicities of aminoglycosides?", a: "Nephrotoxicity and ototoxicity." },
      { q: "Why give aminoglycosides once daily?", a: "Concentration-dependent killing + post-antibiotic effect; reduces toxicity." },
    ],
    mcqs: [
      {
        id: "gen-m1",
        question: "Gentamicin binds to:",
        options: ["30S ribosomal subunit", "50S ribosomal subunit", "DNA gyrase", "Cell wall"],
        answerIndex: 0,
        explanation: "Aminoglycosides bind the 30S subunit, causing mRNA misreading.",
      },
      {
        id: "gen-m2",
        question: "Major toxicity of gentamicin:",
        options: ["Hepatotoxicity", "Nephrotoxicity & ototoxicity", "Cardiotoxicity", "Pulmonary fibrosis"],
        answerIndex: 1,
        explanation: "Nephro- and ototoxicity are the hallmark aminoglycoside adverse effects.",
      },
    ],
  },
  // ─────────────────────────── ANTIMICROBIALS (Anti-TB) ───────────────────────────
  {
    id: "isoniazid",
    name: "Isoniazid (INH)",
    topic: "antimicrobials",
    drugClass: "Antitubercular (first-line)",
    moa: "Inhibits synthesis of mycolic acids in the mycobacterial cell wall (prodrug activated by KatG).",
    uses: ["Active tuberculosis (with rifampicin, pyrazinamide, ethambutol)", "Latent TB prophylaxis"],
    sideEffects: ["Peripheral neuropathy", "Hepatotoxicity", "Drug-induced lupus", "Pyridoxine (B6) deficiency"],
    contraindications: ["Active hepatic disease", "Prior INH-induced hepatitis"],
    interactions: ["Inhibits CYP450 → ↑ phenytoin, carbamazepine", "↑ hepatotoxicity with rifampicin/alcohol"],
    mnemonic: "\"INH → I Nurture Nerves — give B6 (pyridoxine) to prevent neuropathy.\"",
    vivaQuestions: [
      { q: "How is INH-induced peripheral neuropathy prevented?", a: "Co-administer pyridoxine (vitamin B6)." },
      { q: "Which patients acetylate INH slowly?", a: "Slow acetylators — higher risk of neuropathy; fast acetylators risk hepatotoxicity." },
    ],
    mcqs: [
      {
        id: "inh-m1",
        question: "Isoniazid-induced neuropathy is prevented by:",
        options: ["Vitamin B12", "Pyridoxine (B6)", "Folic acid", "Thiamine"],
        answerIndex: 1,
        explanation: "Pyridoxine supplementation prevents INH neuropathy.",
      },
      {
        id: "inh-m2",
        question: "Isoniazid inhibits synthesis of:",
        options: ["Peptidoglycan", "Mycolic acid", "Folic acid", "Protein"],
        answerIndex: 1,
        explanation: "INH blocks mycolic acid synthesis in the mycobacterial cell wall.",
      },
    ],
  },
  // ─────────────────────────── ENDOCRINE ───────────────────────────
  {
    id: "insulin",
    name: "Insulin",
    topic: "endocrine-pharmacology",
    drugClass: "Antidiabetic hormone",
    moa: "Binds insulin (tyrosine kinase) receptors → ↑ glucose uptake (GLUT4), glycogenesis; ↓ gluconeogenesis.",
    uses: ["Type 1 diabetes mellitus", "Type 2 DM (uncontrolled)", "Diabetic ketoacidosis", "Hyperkalemia (with glucose)", "Gestational diabetes"],
    sideEffects: ["Hypoglycemia", "Weight gain", "Lipodystrophy at injection site", "Local allergy"],
    contraindications: ["Hypoglycemia"],
    interactions: ["β-blockers mask hypoglycemia", "Corticosteroids/thiazides raise glucose (↓ effect)"],
    mnemonic: "\"Insulin drives K⁺ INto cells\" — used in hyperkalemia.",
    vivaQuestions: [
      { q: "Which insulin is used IV in DKA?", a: "Regular (short-acting) insulin." },
      { q: "First sign of insulin overdose?", a: "Hypoglycemia — sweating, tremor, tachycardia, confusion." },
    ],
    mcqs: [
      {
        id: "ins-m1",
        question: "Most common adverse effect of insulin:",
        options: ["Hyperglycemia", "Hypoglycemia", "Hypertension", "Weight loss"],
        answerIndex: 1,
        explanation: "Hypoglycemia is the main and most dangerous adverse effect.",
      },
      {
        id: "ins-m2",
        question: "Insulin used in diabetic ketoacidosis is:",
        options: ["Insulin glargine", "Regular insulin (IV)", "NPH insulin", "Insulin detemir"],
        answerIndex: 1,
        explanation: "Short-acting regular insulin is given IV in DKA.",
      },
    ],
  },
  {
    id: "metformin",
    name: "Metformin",
    topic: "endocrine-pharmacology",
    drugClass: "Biguanide (oral antidiabetic)",
    moa: "Activates AMPK → ↓ hepatic gluconeogenesis, ↑ peripheral insulin sensitivity; no insulin secretion.",
    uses: ["Type 2 diabetes (first-line)", "Polycystic ovarian syndrome (PCOS)", "Prediabetes"],
    sideEffects: ["GI upset / diarrhea", "Metallic taste", "Vitamin B12 deficiency", "Lactic acidosis (rare)"],
    contraindications: ["Renal impairment (eGFR <30)", "Metabolic acidosis", "Hold before IV contrast"],
    interactions: ["Contrast dye → lactic acidosis risk", "Alcohol ↑ lactic acidosis"],
    mnemonic: "\"Metformin doesn't cause hypoglycemia (no insulin release) — weight-neutral, first-line.\"",
    vivaQuestions: [
      { q: "Why is metformin first-line in T2DM?", a: "Effective, weight-neutral, no hypoglycemia, cardiovascular benefit, cheap." },
      { q: "Most serious adverse effect of metformin?", a: "Lactic acidosis (rare but potentially fatal)." },
    ],
    mcqs: [
      {
        id: "met-m1",
        question: "Metformin's main mechanism is:",
        options: ["Stimulating insulin release", "Decreasing hepatic gluconeogenesis", "Blocking glucose absorption fully", "Increasing glucagon"],
        answerIndex: 1,
        explanation: "Metformin decreases hepatic glucose output via AMPK activation.",
      },
      {
        id: "met-m2",
        question: "Metformin, unlike sulfonylureas, does NOT cause:",
        options: ["Diarrhea", "Hypoglycemia", "B12 deficiency", "Metallic taste"],
        answerIndex: 1,
        explanation: "Metformin does not stimulate insulin release, so monotherapy rarely causes hypoglycemia.",
      },
    ],
  },
  // ─────────────────────────── NSAIDs & ANALGESICS ───────────────────────────
  {
    id: "aspirin",
    name: "Aspirin",
    topic: "nsaids-analgesics",
    drugClass: "NSAID (non-selective COX inhibitor)",
    moa: "Irreversibly acetylates COX-1 & COX-2 → ↓ prostaglandins & thromboxane A2.",
    uses: ["Antiplatelet (MI/stroke prevention)", "Analgesic", "Antipyretic", "Anti-inflammatory (high dose)"],
    sideEffects: ["Gastric ulcer / bleeding", "Tinnitus (salicylism)", "Reye's syndrome in children", "Bronchospasm"],
    contraindications: ["Children with viral fever (Reye's)", "Peptic ulcer disease", "Bleeding disorders", "Gout"],
    interactions: ["↑ bleeding with warfarin", "↓ effect of uricosurics", "Displaces other protein-bound drugs"],
    mnemonic: "\"Aspirin is Antiplatelet — irreversibly blocks COX for the platelet's life (~7–10 days).\"",
    vivaQuestions: [
      { q: "Why does low-dose aspirin work as an antiplatelet?", a: "It irreversibly inhibits platelet COX-1 → ↓ thromboxane A2; platelets can't resynthesize enzyme." },
      { q: "Why avoid aspirin in children with viral fever?", a: "Risk of Reye's syndrome (hepatic encephalopathy)." },
    ],
    mcqs: [
      {
        id: "asp-m1",
        question: "Aspirin inhibits cyclooxygenase:",
        options: ["Reversibly", "Irreversibly", "Only COX-2", "Not at all"],
        answerIndex: 1,
        explanation: "Aspirin irreversibly acetylates COX — unique among NSAIDs.",
      },
      {
        id: "asp-m2",
        question: "Aspirin is avoided in children due to risk of:",
        options: ["Gray baby syndrome", "Reye's syndrome", "Kernicterus", "Tendon rupture"],
        answerIndex: 1,
        explanation: "Aspirin in children with viral illness can cause Reye's syndrome.",
      },
    ],
  },
  // ─────────────────────────── AUTACOIDS ───────────────────────────
  {
    id: "loratadine",
    name: "Loratadine",
    topic: "autacoids",
    drugClass: "Second-generation H1 antihistamine",
    moa: "Selectively blocks peripheral H1 histamine receptors; poor CNS penetration → non-sedating.",
    uses: ["Allergic rhinitis", "Urticaria", "Chronic allergic conditions"],
    sideEffects: ["Headache", "Dry mouth", "Mild fatigue (uncommon)"],
    contraindications: ["Hypersensitivity", "Caution in severe hepatic impairment"],
    interactions: ["Minimal; CYP3A4 inhibitors may ↑ levels"],
    mnemonic: "\"2nd-gen antihistamines are Less sedating (loratadine, cetirizine, fexofenadine).\"",
    vivaQuestions: [
      { q: "Why is loratadine non-sedating unlike chlorpheniramine?", a: "It doesn't readily cross the blood-brain barrier (peripheral H1 selectivity)." },
      { q: "Difference between 1st and 2nd generation antihistamines?", a: "1st-gen (diphenhydramine) sedate & have antimuscarinic effects; 2nd-gen are non-sedating and selective." },
    ],
    mcqs: [
      {
        id: "lor-m1",
        question: "Loratadine is preferred over diphenhydramine because it is:",
        options: ["More potent", "Non-sedating", "Cheaper", "Longer studied"],
        answerIndex: 1,
        explanation: "Second-generation antihistamines are non-sedating (poor CNS entry).",
      },
      {
        id: "lor-m2",
        question: "Loratadine blocks which receptor?",
        options: ["H2", "H1", "Muscarinic", "Serotonin"],
        answerIndex: 1,
        explanation: "It is a selective peripheral H1 antagonist.",
      },
    ],
  },
  {
    id: "cetirizine",
    name: "Cetirizine",
    topic: "autacoids",
    drugClass: "Second-generation H1 antihistamine (active metabolite of hydroxyzine)",
    moa: "Selectively blocks peripheral H1 receptors; crosses the blood-brain barrier slightly more than loratadine, so it can cause mild sedation.",
    uses: ["Allergic rhinitis", "Chronic urticaria", "Allergic conjunctivitis", "Atopic dermatitis itch"],
    sideEffects: ["Mild sedation (most of the 2nd-gen)", "Dry mouth", "Headache"],
    contraindications: ["Hypersensitivity", "Dose reduction in renal impairment"],
    interactions: ["Additive CNS depression with alcohol and sedatives"],
    mnemonic: "\"Cetirizine — the slightly sleepy second-gen.\"",
    vivaQuestions: [
      { q: "Which 2nd-generation antihistamine is most likely to sedate?", a: "Cetirizine — it crosses the BBB a little more than loratadine/fexofenadine." },
      { q: "Cetirizine is the active metabolite of which drug?", a: "Hydroxyzine." },
    ],
    mcqs: [
      {
        id: "cet-m1",
        question: "Cetirizine is the active metabolite of:",
        options: ["Loratadine", "Hydroxyzine", "Promethazine", "Diphenhydramine"],
        answerIndex: 1,
        explanation: "Cetirizine is the carboxylated active metabolite of hydroxyzine.",
      },
      {
        id: "cet-m2",
        question: "Compared with loratadine, cetirizine more often causes:",
        options: ["Sedation", "Arrhythmia", "Photosensitivity", "Weight gain"],
        answerIndex: 0,
        explanation: "Cetirizine penetrates the CNS slightly more, so mild sedation is commoner.",
      },
    ],
  },
  {
    id: "fexofenadine",
    name: "Fexofenadine",
    topic: "autacoids",
    drugClass: "Second-generation H1 antihistamine (active metabolite of terfenadine)",
    moa: "Selective peripheral H1 blockade with negligible CNS entry (non-sedating) and no cardiotoxicity, unlike its withdrawn parent terfenadine.",
    uses: ["Allergic rhinitis", "Chronic urticaria"],
    sideEffects: ["Headache", "Essentially non-sedating", "Nausea (uncommon)"],
    contraindications: ["Hypersensitivity"],
    interactions: ["Fruit juices (grapefruit, apple, orange) reduce absorption", "Aluminium/magnesium antacids reduce absorption"],
    mnemonic: "\"Fexofenadine — take with water, not juice.\"",
    vivaQuestions: [
      { q: "Why was terfenadine withdrawn while fexofenadine is safe?", a: "Terfenadine caused QT prolongation and torsades when its metabolism was blocked; fexofenadine is its safe active metabolite with no cardiotoxicity." },
      { q: "What reduces fexofenadine absorption?", a: "Fruit juices and aluminium/magnesium-containing antacids." },
    ],
    mcqs: [
      {
        id: "fex-m1",
        question: "Fexofenadine is the safe active metabolite of:",
        options: ["Astemizole", "Terfenadine", "Loratadine", "Cetirizine"],
        answerIndex: 1,
        explanation: "Terfenadine was cardiotoxic; its metabolite fexofenadine is not.",
      },
      {
        id: "fex-m2",
        question: "Absorption of fexofenadine is decreased by:",
        options: ["Grapefruit juice", "A high-fat meal", "Vitamin C", "Iron tablets"],
        answerIndex: 0,
        explanation: "Fruit juices inhibit the OATP transporter that takes up fexofenadine.",
      },
    ],
  },
  {
    id: "diphenhydramine",
    name: "Diphenhydramine",
    topic: "autacoids",
    drugClass: "First-generation H1 antihistamine (ethanolamine)",
    moa: "Blocks central and peripheral H1 receptors and has antimuscarinic activity; high lipid solubility crosses the BBB, causing sedation.",
    uses: ["Allergic reactions", "Motion sickness", "Sedation / insomnia (OTC)", "Drug-induced parkinsonism", "Antitussive"],
    sideEffects: ["Sedation", "Dry mouth", "Blurred vision", "Urinary retention", "Constipation"],
    contraindications: ["Narrow-angle glaucoma", "Benign prostatic hyperplasia", "Neonates"],
    interactions: ["Additive sedation with CNS depressants", "Additive antimuscarinic effect with TCAs and atropine"],
    mnemonic: "\"1st-gen = Drowsy + Dry (sedation plus antimuscarinic).\"",
    vivaQuestions: [
      { q: "Why does diphenhydramine sedate?", a: "It is lipid-soluble, crosses the BBB and blocks central H1 receptors." },
      { q: "Why is it useful in drug-induced parkinsonism?", a: "Its antimuscarinic action counters extrapyramidal symptoms." },
    ],
    mcqs: [
      {
        id: "dip-m1",
        question: "Sedation from diphenhydramine is due to blockade of:",
        options: ["Peripheral H1 receptors", "Central H1 receptors", "H2 receptors", "Dopamine receptors"],
        answerIndex: 1,
        explanation: "Central H1 blockade after crossing the blood-brain barrier causes sedation.",
      },
      {
        id: "dip-m2",
        question: "Diphenhydramine helps motion sickness mainly through its:",
        options: ["β-blocking effect", "Central antimuscarinic/antihistaminic action", "Diuretic effect", "α-agonist effect"],
        answerIndex: 1,
        explanation: "Central H1 and muscarinic blockade damps vestibular input.",
      },
    ],
  },
  {
    id: "chlorpheniramine",
    name: "Chlorpheniramine",
    topic: "autacoids",
    drugClass: "First-generation H1 antihistamine (alkylamine)",
    moa: "Blocks central and peripheral H1 receptors; as an alkylamine it sedates less than the ethanolamine diphenhydramine.",
    uses: ["Allergic rhinitis", "Urticaria", "Common-cold combinations"],
    sideEffects: ["Sedation (less than diphenhydramine)", "Dry mouth", "Dizziness"],
    contraindications: ["Narrow-angle glaucoma", "Benign prostatic hyperplasia", "Neonates"],
    interactions: ["Additive CNS depression", "MAO inhibitors intensify antimuscarinic effects"],
    mnemonic: "\"Chlorpheniramine — the least-sedating first-gen.\"",
    vivaQuestions: [
      { q: "Which first-generation antihistamine sedates the least?", a: "Chlorpheniramine (an alkylamine)." },
    ],
    mcqs: [
      {
        id: "chlor-m1",
        question: "Among first-generation antihistamines, least sedation is seen with:",
        options: ["Diphenhydramine", "Promethazine", "Chlorpheniramine", "Hydroxyzine"],
        answerIndex: 2,
        explanation: "Alkylamines such as chlorpheniramine are the least sedating first-gen agents.",
      },
    ],
  },
  {
    id: "promethazine",
    name: "Promethazine",
    topic: "autacoids",
    drugClass: "First-generation H1 antihistamine (phenothiazine)",
    moa: "Blocks H1 receptors with strong antimuscarinic, antiemetic (central D2 block) and sedative effects.",
    uses: ["Motion sickness", "Nausea and vomiting", "Sedation", "Allergic conditions", "Pruritus"],
    sideEffects: ["Marked sedation", "Antimuscarinic effects", "Photosensitivity", "Respiratory depression in infants"],
    contraindications: ["Children under 2 years (fatal respiratory depression)", "Narrow-angle glaucoma", "Benign prostatic hyperplasia"],
    interactions: ["Additive CNS depression", "Additive with other anticholinergics", "Lowers seizure threshold"],
    mnemonic: "\"Promethazine — Phenothiazine: sedative + antiemetic.\"",
    vivaQuestions: [
      { q: "Why is promethazine contraindicated in children under 2?", a: "It can cause fatal respiratory depression." },
      { q: "How does promethazine act as an antiemetic?", a: "Central D2, H1 and muscarinic blockade in the vomiting centre and vestibular pathway." },
    ],
    mcqs: [
      {
        id: "prom-m1",
        question: "Promethazine is contraindicated in children under 2 years because of:",
        options: ["Hepatotoxicity", "Fatal respiratory depression", "Nephrotoxicity", "Agranulocytosis"],
        answerIndex: 1,
        explanation: "Promethazine can cause fatal respiratory depression in infants.",
      },
    ],
  },
  {
    id: "cyproheptadine",
    name: "Cyproheptadine",
    topic: "autacoids",
    drugClass: "First-generation H1 antihistamine with 5-HT2 antagonism",
    moa: "Blocks H1 and 5-HT2 receptors; 5-HT2 blockade stimulates appetite and reverses serotonin excess.",
    uses: ["Allergic conditions", "Appetite stimulation", "Serotonin syndrome (antidote)", "Cold urticaria"],
    sideEffects: ["Sedation", "Weight gain", "Dry mouth", "Dizziness"],
    contraindications: ["Narrow-angle glaucoma", "Benign prostatic hyperplasia", "Neonates"],
    interactions: ["Additive CNS depression", "May blunt the effect of SSRIs"],
    mnemonic: "\"Cyproheptadine — blocks Histamine + Serotonin → hunger + serotonin-syndrome antidote.\"",
    vivaQuestions: [
      { q: "Which drug is used in serotonin syndrome?", a: "Cyproheptadine, a 5-HT2 antagonist." },
      { q: "Why does cyproheptadine increase appetite?", a: "5-HT2 blockade in the hypothalamic satiety centre." },
    ],
    mcqs: [
      {
        id: "cypro-m1",
        question: "The drug used to treat serotonin syndrome is:",
        options: ["Ondansetron", "Cyproheptadine", "Sumatriptan", "Fluoxetine"],
        answerIndex: 1,
        explanation: "Cyproheptadine blocks 5-HT2 receptors and is the antidote for serotonin syndrome.",
      },
      {
        id: "cypro-m2",
        question: "Cyproheptadine stimulates appetite by blocking:",
        options: ["H2 receptors", "5-HT2 receptors", "Dopamine receptors", "GABA receptors"],
        answerIndex: 1,
        explanation: "5-HT2 blockade in the satiety centre increases appetite.",
      },
    ],
  },
  {
    id: "ondansetron",
    name: "Ondansetron",
    topic: "autacoids",
    drugClass: "5-HT3 receptor antagonist (antiemetic)",
    moa: "Blocks 5-HT3 receptors on vagal afferents and in the chemoreceptor trigger zone, producing a potent antiemetic effect.",
    uses: ["Chemotherapy-induced nausea and vomiting", "Post-operative nausea and vomiting", "Radiation-induced vomiting"],
    sideEffects: ["Headache", "Constipation", "QT prolongation", "Dizziness"],
    contraindications: ["Congenital long-QT syndrome", "Concurrent apomorphine"],
    interactions: ["Additive QT prolongation with other QT-prolonging drugs", "Severe hypotension with apomorphine"],
    mnemonic: "\"The 'setrons' block 5-HT3 and stop vomiting.\"",
    vivaQuestions: [
      { q: "How does ondansetron prevent vomiting?", a: "Central and peripheral 5-HT3 receptor blockade." },
      { q: "What is its important cardiac adverse effect?", a: "QT-interval prolongation." },
    ],
    mcqs: [
      {
        id: "ond-m1",
        question: "Ondansetron acts by blocking:",
        options: ["5-HT1 receptors", "5-HT3 receptors", "Dopamine D2 receptors", "H1 receptors"],
        answerIndex: 1,
        explanation: "Ondansetron is a selective 5-HT3 antagonist.",
      },
      {
        id: "ond-m2",
        question: "A cardiac adverse effect of ondansetron is:",
        options: ["Bradycardia", "QT prolongation", "Complete heart block", "Hypertension"],
        answerIndex: 1,
        explanation: "Ondansetron can prolong the QT interval.",
      },
    ],
  },
  {
    id: "sumatriptan",
    name: "Sumatriptan",
    topic: "autacoids",
    drugClass: "5-HT1B/1D receptor agonist (triptan)",
    moa: "Agonist at 5-HT1B/1D receptors → cranial vasoconstriction and reduced release of trigeminal neuropeptides, aborting a migraine.",
    uses: ["Acute migraine", "Cluster headache"],
    sideEffects: ["Chest tightness / pressure", "Paresthesia", "Flushing", "Coronary vasospasm (rare)"],
    contraindications: ["Ischemic heart disease", "Prinzmetal (variant) angina", "Uncontrolled hypertension", "Recent ergot use"],
    interactions: ["Ergot alkaloids (additive vasospasm — separate by 24 h)", "MAO inhibitors raise levels", "SSRIs/SNRIs risk serotonin syndrome"],
    mnemonic: "\"Triptans Terminate migraine — but not in ischemic heart disease.\"",
    vivaQuestions: [
      { q: "Why is sumatriptan contraindicated in ischemic heart disease?", a: "It causes coronary vasoconstriction via 5-HT1B receptors on vascular smooth muscle." },
      { q: "Why must triptans and ergotamine be separated by 24 hours?", a: "Their vasoconstrictor effects are additive and can cause dangerous vasospasm." },
    ],
    mcqs: [
      {
        id: "suma-m1",
        question: "Sumatriptan aborts migraine by acting as an agonist at:",
        options: ["5-HT2 receptors", "5-HT1B/1D receptors", "5-HT3 receptors", "5-HT4 receptors"],
        answerIndex: 1,
        explanation: "Triptans are 5-HT1B/1D agonists causing cranial vasoconstriction.",
      },
      {
        id: "suma-m2",
        question: "Sumatriptan is contraindicated in:",
        options: ["Migraine with aura", "Ischemic heart disease", "Young adults", "Menstrual migraine"],
        answerIndex: 1,
        explanation: "Coronary vasoconstriction makes it unsafe in ischemic heart disease.",
      },
    ],
  },
  {
    id: "ergotamine",
    name: "Ergotamine",
    topic: "autacoids",
    drugClass: "Ergot alkaloid (partial agonist at 5-HT, α-adrenergic and dopamine receptors)",
    moa: "Non-selective 5-HT1 and α-adrenergic agonism produces cranial vasoconstriction that aborts migraine; prolonged action risks sustained vasospasm.",
    uses: ["Acute migraine (often with caffeine)", "Cluster headache"],
    sideEffects: ["Nausea and vomiting", "Peripheral ischemia (ergotism)", "Paresthesia", "Vasospasm"],
    contraindications: ["Pregnancy", "Peripheral vascular disease", "Ischemic heart disease", "Hepatic or renal impairment"],
    interactions: ["CYP3A4 inhibitors (macrolides, azoles, protease inhibitors) → severe ergotism", "Triptans (additive vasospasm)"],
    mnemonic: "\"Ergot = vasoconstriction → gangrene; never in pregnancy.\"",
    vivaQuestions: [
      { q: "What is ergotism?", a: "Severe peripheral vasospasm from ergot excess → cold, painful, potentially gangrenous limbs." },
      { q: "Why is ergotamine contraindicated in pregnancy?", a: "It is a uterine stimulant (oxytocic) and vasoconstrictor." },
    ],
    mcqs: [
      {
        id: "ergo-m1",
        question: "Prolonged or excessive ergotamine use can cause:",
        options: ["Peripheral gangrene", "Pulmonary fibrosis", "Renal stones", "Hemolytic anemia"],
        answerIndex: 0,
        explanation: "Sustained vasoconstriction (ergotism) can progress to peripheral gangrene.",
      },
    ],
  },
  {
    id: "misoprostol",
    name: "Misoprostol",
    topic: "autacoids",
    drugClass: "Prostaglandin E1 (PGE1) analogue",
    moa: "PGE1 agonist that reduces gastric acid secretion and increases protective mucus and bicarbonate; also stimulates uterine contraction.",
    uses: ["Prevention of NSAID-induced peptic ulcers", "Medical abortion (with mifepristone)", "Cervical ripening / labour induction", "Postpartum hemorrhage"],
    sideEffects: ["Diarrhea", "Abdominal cramps", "Uterine bleeding", "Miscarriage"],
    contraindications: ["Pregnancy (when used for ulcer prevention)", "Hypersensitivity"],
    interactions: ["Magnesium-containing antacids worsen diarrhea"],
    mnemonic: "\"Misoprostol — Mucus & bicarbonate up; Miscarriage risk.\"",
    vivaQuestions: [
      { q: "Why is misoprostol given with long-term NSAIDs?", a: "It replaces the protective prostaglandins NSAIDs inhibit, preventing gastric ulcers." },
      { q: "Why is it contraindicated in pregnancy for ulcer use?", a: "It causes uterine contractions and can induce abortion." },
    ],
    mcqs: [
      {
        id: "miso-m1",
        question: "Misoprostol prevents NSAID-induced ulcers because it is a:",
        options: ["PGE1 analogue", "H2 blocker", "Proton pump inhibitor", "Muscarinic antagonist"],
        answerIndex: 0,
        explanation: "As a PGE1 analogue it restores cytoprotective prostaglandin activity.",
      },
    ],
  },
  {
    id: "latanoprost",
    name: "Latanoprost",
    topic: "autacoids",
    drugClass: "Prostaglandin F2α (PGF2α) analogue",
    moa: "PGF2α agonist that increases uveoscleral outflow of aqueous humour, lowering intraocular pressure.",
    uses: ["Open-angle glaucoma (first-line topical)", "Ocular hypertension"],
    sideEffects: ["Iris hyperpigmentation (brown)", "Eyelash lengthening and darkening", "Conjunctival hyperemia", "Periorbital pigmentation"],
    contraindications: ["Hypersensitivity", "Caution in uveitis and macular edema"],
    interactions: ["Minimal systemic interaction (topical)"],
    mnemonic: "\"Latanoprost — Longer, darker lashes; brown iris; lowers eye pressure.\"",
    vivaQuestions: [
      { q: "How does latanoprost lower intraocular pressure?", a: "By increasing uveoscleral outflow of aqueous humour." },
      { q: "What is its characteristic cosmetic side effect?", a: "Iris and periorbital hyperpigmentation with eyelash growth." },
    ],
    mcqs: [
      {
        id: "lata-m1",
        question: "Latanoprost lowers intraocular pressure by:",
        options: ["Decreasing aqueous production", "Increasing uveoscleral outflow", "Blocking β receptors", "Constricting the pupil"],
        answerIndex: 1,
        explanation: "PGF2α analogues increase uveoscleral outflow of aqueous humour.",
      },
      {
        id: "lata-m2",
        question: "A characteristic side effect of latanoprost is:",
        options: ["Iris hyperpigmentation", "Cataract", "Corneal ulcer", "Night blindness"],
        answerIndex: 0,
        explanation: "Increased iris melanin causes brown pigmentation, along with eyelash growth.",
      },
    ],
  },

  // ═══════════════════ ADDED HIGH-YIELD DRUGS ═══════════════════

  // ── Autonomic nervous system ──
  {
    id: "noradrenaline",
    name: "Noradrenaline (Norepinephrine)",
    topic: "autonomic-nervous-system",
    drugClass: "Adrenergic agonist (α1, α2, β1 > β2)",
    moa: "Potent α1 (vasoconstriction) and β1 (cardiac) agonist with minimal β2 activity.",
    uses: ["Septic / distributive shock (vasopressor of choice)", "Severe hypotension"],
    sideEffects: ["Reflex bradycardia", "Hypertension", "Tissue necrosis on extravasation", "Reduced organ perfusion"],
    contraindications: ["Hypovolaemia (correct first)", "Mesenteric/peripheral vascular thrombosis"],
    interactions: ["MAO inhibitors & TCAs potentiate pressor effect"],
    mnemonic: "\"NORad = NO β2 → mainly vasoconstriction; first-line in septic shock.\"",
    vivaQuestions: [
      { q: "Why does noradrenaline cause reflex bradycardia?", a: "Strong α1 vasoconstriction raises BP → baroreceptor reflex → vagal slowing of the heart." },
      { q: "Vasopressor of choice in septic shock?", a: "Noradrenaline." },
    ],
    mcqs: [
      {
        id: "nor-m1",
        question: "Noradrenaline acts mainly on:",
        options: ["β2 receptors", "α1 and β1 receptors", "Muscarinic receptors", "Dopamine receptors"],
        answerIndex: 1,
        explanation: "Noradrenaline is an α1/β1 agonist with negligible β2 action.",
      },
      {
        id: "nor-m2",
        question: "Noradrenaline is the vasopressor of choice in:",
        options: ["Cardiogenic shock only", "Septic shock", "Anaphylaxis", "Hypovolaemic shock"],
        answerIndex: 1,
        explanation: "Noradrenaline is first-line in septic (distributive) shock.",
      },
    ],
  },
  {
    id: "salbutamol",
    name: "Salbutamol (Albuterol)",
    topic: "autonomic-nervous-system",
    drugClass: "Selective β2 adrenergic agonist (SABA)",
    moa: "Stimulates β2 receptors on bronchial smooth muscle → bronchodilation.",
    uses: ["Acute asthma / bronchospasm (reliever)", "COPD", "Hyperkalaemia (drives K⁺ into cells)"],
    sideEffects: ["Tremor", "Tachycardia / palpitations", "Hypokalaemia", "Anxiety", "Headache"],
    contraindications: ["Caution in tachyarrhythmia, ischaemic heart disease"],
    interactions: ["Non-selective β-blockers antagonise its effect", "Additive hypokalaemia with diuretics"],
    mnemonic: "\"SAL-butamol Saves the Airway (β2 = 2 lungs).\"",
    vivaQuestions: [
      { q: "Why does salbutamol cause tremor?", a: "β2 stimulation of skeletal muscle." },
      { q: "Why avoid propranolol in asthmatics on salbutamol?", a: "Non-selective β-blockade blocks β2 bronchodilation and can trigger bronchospasm." },
    ],
    mcqs: [
      {
        id: "sal-m1",
        question: "Salbutamol relieves asthma by acting on:",
        options: ["β1 receptors", "β2 receptors", "M3 receptors", "α1 receptors"],
        answerIndex: 1,
        explanation: "β2 agonism relaxes bronchial smooth muscle.",
      },
      {
        id: "sal-m2",
        question: "A metabolic side effect of high-dose salbutamol:",
        options: ["Hyperkalaemia", "Hypokalaemia", "Hypernatraemia", "Hypocalcaemia"],
        answerIndex: 1,
        explanation: "β2 agonists drive potassium into cells, causing hypokalaemia.",
      },
    ],
  },

  // ── Cardiovascular ──
  {
    id: "atenolol",
    name: "Atenolol",
    topic: "cardiovascular-drugs",
    drugClass: "Cardioselective β1 blocker (hydrophilic)",
    moa: "Selectively blocks β1 receptors → ↓ heart rate, contractility and renin release.",
    uses: ["Hypertension", "Angina", "Post-MI", "Supraventricular arrhythmias"],
    sideEffects: ["Bradycardia", "Fatigue", "Cold extremities", "Masks hypoglycaemia"],
    contraindications: ["Severe asthma", "Heart block (2nd/3rd degree)", "Decompensated heart failure"],
    interactions: ["Verapamil/diltiazem → bradycardia/AV block", "NSAIDs blunt antihypertensive effect"],
    mnemonic: "\"Atenolol is hydrophilic → fewer CNS effects than propranolol.\"",
    vivaQuestions: [
      { q: "Why does atenolol cause fewer CNS side effects?", a: "It is hydrophilic and crosses the blood-brain barrier poorly." },
      { q: "Is atenolol selective?", a: "Yes — β1-selective (cardioselective) at usual doses." },
    ],
    mcqs: [
      {
        id: "ate-m1",
        question: "Atenolol is a:",
        options: ["Non-selective β-blocker", "β1-selective blocker", "α-blocker", "β2 agonist"],
        answerIndex: 1,
        explanation: "Atenolol is cardioselective (β1).",
      },
      {
        id: "ate-m2",
        question: "Compared with propranolol, atenolol has:",
        options: ["More CNS side effects", "Fewer CNS side effects", "More bronchospasm", "Shorter action"],
        answerIndex: 1,
        explanation: "Being hydrophilic, atenolol penetrates the CNS less.",
      },
    ],
  },
  {
    id: "hydrochlorothiazide",
    name: "Hydrochlorothiazide",
    topic: "cardiovascular-drugs",
    drugClass: "Thiazide diuretic",
    moa: "Inhibits Na⁺/Cl⁻ symporter in the distal convoluted tubule → ↑ sodium & water excretion.",
    uses: ["Hypertension (first-line)", "Mild oedema / heart failure", "Nephrogenic diabetes insipidus", "Recurrent calcium stones"],
    sideEffects: ["Hypokalaemia", "Hyponatraemia", "Hyperglycaemia", "Hyperuricaemia (gout)", "Hypercalcaemia", "Hyperlipidaemia"],
    contraindications: ["Gout", "Severe renal failure", "Sulfonamide allergy (caution)"],
    interactions: ["Digoxin toxicity via hypokalaemia", "Lithium retention", "NSAIDs ↓ effect"],
    mnemonic: "\"Thiazides cause hyper-GLUC: Glycaemia, Lipidaemia, Uricaemia, Calcaemia. Loops LOSE calcium, thiazides KEEP it.\"",
    vivaQuestions: [
      { q: "How do thiazides differ from loop diuretics on calcium?", a: "Thiazides cause hypercalcaemia (retain Ca²⁺); loops cause hypocalcaemia." },
      { q: "Where do thiazides act?", a: "The distal convoluted tubule (Na⁺/Cl⁻ symporter)." },
    ],
    mcqs: [
      {
        id: "hctz-m1",
        question: "Hydrochlorothiazide acts on the:",
        options: ["Loop of Henle", "Distal convoluted tubule", "Collecting duct", "Proximal tubule"],
        answerIndex: 1,
        explanation: "Thiazides block the Na-Cl symporter in the DCT.",
      },
      {
        id: "hctz-m2",
        question: "Thiazides cause all EXCEPT:",
        options: ["Hyperglycaemia", "Hyperuricaemia", "Hypocalcaemia", "Hypokalaemia"],
        answerIndex: 2,
        explanation: "Thiazides cause HYPERcalcaemia (calcium is retained).",
      },
    ],
  },
  {
    id: "enalapril",
    name: "Enalapril",
    topic: "cardiovascular-drugs",
    drugClass: "ACE inhibitor",
    moa: "Inhibits angiotensin-converting enzyme → ↓ angiotensin II & aldosterone; ↑ bradykinin.",
    uses: ["Hypertension", "Heart failure", "Diabetic nephropathy", "Post-MI"],
    sideEffects: ["Dry cough (bradykinin)", "Hyperkalaemia", "First-dose hypotension", "Angioedema", "Renal impairment"],
    contraindications: ["Pregnancy", "Bilateral renal artery stenosis", "Angioedema history", "Hyperkalaemia"],
    interactions: ["K⁺-sparing diuretics → hyperkalaemia", "NSAIDs → ↓ effect + renal injury", "Lithium levels rise"],
    mnemonic: "\"ACE inhibitor SEs — CAPTOPRIL: Cough, Angioedema, Potassium ↑, Taste change, Orthostatic hypotension, Pregnancy contraindication, Renal impairment, Increased renin.\"",
    vivaQuestions: [
      { q: "Why do ACE inhibitors cause a dry cough?", a: "Accumulation of bradykinin (normally degraded by ACE)." },
      { q: "Why are ACE inhibitors contraindicated in pregnancy?", a: "They are teratogenic — cause fetal renal damage and oligohydramnios." },
    ],
    mcqs: [
      {
        id: "ena-m1",
        question: "The dry cough of enalapril is due to:",
        options: ["Histamine", "Bradykinin accumulation", "Substance P deficiency", "Prostaglandin loss"],
        answerIndex: 1,
        explanation: "ACE normally breaks down bradykinin; inhibition raises it → cough.",
      },
      {
        id: "ena-m2",
        question: "Enalapril is contraindicated in:",
        options: ["Heart failure", "Diabetic nephropathy", "Bilateral renal artery stenosis", "Hypertension"],
        answerIndex: 2,
        explanation: "It can precipitate acute renal failure in bilateral renal artery stenosis.",
      },
    ],
  },
  {
    id: "nitroglycerin",
    name: "Nitroglycerin (GTN)",
    topic: "cardiovascular-drugs",
    drugClass: "Organic nitrate (vasodilator)",
    moa: "Releases nitric oxide → ↑ cGMP → venodilation → ↓ preload and myocardial O₂ demand.",
    uses: ["Acute angina (sublingual)", "Acute heart failure / pulmonary oedema", "Hypertensive emergency"],
    sideEffects: ["Throbbing headache", "Postural hypotension", "Reflex tachycardia", "Flushing", "Tolerance"],
    contraindications: ["Use of PDE-5 inhibitors (sildenafil) → severe hypotension", "Hypotension", "Raised intracranial pressure"],
    interactions: ["Sildenafil/tadalafil → life-threatening hypotension", "Additive with antihypertensives"],
    mnemonic: "\"Nitrates dilate Veins first → ↓ preload. Never with sildenafil.\"",
    vivaQuestions: [
      { q: "Why is nitroglycerin given sublingually for angina?", a: "To bypass extensive first-pass hepatic metabolism and act rapidly." },
      { q: "How is nitrate tolerance prevented?", a: "By providing a daily nitrate-free interval (8–12 h)." },
    ],
    mcqs: [
      {
        id: "gtn-m1",
        question: "Nitroglycerin relieves angina mainly by:",
        options: ["Increasing preload", "Reducing preload via venodilation", "Increasing heart rate", "Coronary steal"],
        answerIndex: 1,
        explanation: "Venodilation lowers preload and myocardial oxygen demand.",
      },
      {
        id: "gtn-m2",
        question: "Nitroglycerin is dangerous when combined with:",
        options: ["Aspirin", "Sildenafil", "Metoprolol", "Atorvastatin"],
        answerIndex: 1,
        explanation: "PDE-5 inhibitors + nitrates cause profound hypotension.",
      },
    ],
  },

  // ── CNS ──
  {
    id: "haloperidol",
    name: "Haloperidol",
    topic: "cns-drugs",
    drugClass: "Typical antipsychotic (butyrophenone)",
    moa: "Blocks dopamine D2 receptors in the mesolimbic pathway.",
    uses: ["Schizophrenia / acute psychosis", "Acute agitation / delirium", "Tourette syndrome", "Intractable hiccups"],
    sideEffects: ["Extrapyramidal symptoms (dystonia, parkinsonism, akathisia)", "Tardive dyskinesia", "Neuroleptic malignant syndrome", "Hyperprolactinaemia", "QT prolongation"],
    contraindications: ["Parkinson's disease", "Severe CNS depression", "Prolonged QT"],
    interactions: ["Additive QT prolongation", "Additive CNS depression with sedatives"],
    mnemonic: "\"Typicals block D2 → EPS & ↑ prolactin. NMS: fever, rigidity, autonomic instability.\"",
    vivaQuestions: [
      { q: "What are extrapyramidal side effects?", a: "Movement disorders from D2 blockade: acute dystonia, parkinsonism, akathisia and tardive dyskinesia." },
      { q: "What is neuroleptic malignant syndrome?", a: "A rare, life-threatening reaction: hyperthermia, muscle rigidity, altered mental state, autonomic instability and raised CK." },
    ],
    mcqs: [
      {
        id: "hal-m1",
        question: "Haloperidol acts mainly by blocking:",
        options: ["Serotonin receptors", "Dopamine D2 receptors", "GABA receptors", "Muscarinic receptors"],
        answerIndex: 1,
        explanation: "It is a potent D2 antagonist.",
      },
      {
        id: "hal-m2",
        question: "A hallmark adverse effect of haloperidol:",
        options: ["Weight gain mainly", "Extrapyramidal symptoms", "Diarrhoea", "Hypertension"],
        answerIndex: 1,
        explanation: "Typical antipsychotics prominently cause EPS.",
      },
    ],
  },
  {
    id: "lidocaine",
    name: "Lidocaine (Lignocaine)",
    topic: "cns-drugs",
    drugClass: "Local anaesthetic (amide) / Class IB antiarrhythmic",
    moa: "Blocks voltage-gated Na⁺ channels → prevents nerve impulse conduction.",
    uses: ["Local / regional anaesthesia", "Ventricular arrhythmias (esp. post-MI)", "Nerve blocks"],
    sideEffects: ["Perioral numbness / tingling", "Dizziness", "Seizures (high dose)", "Cardiac depression", "Hypotension"],
    contraindications: ["Heart block", "Hypersensitivity to amide anaesthetics"],
    interactions: ["Adrenaline added to prolong local action & limit spread", "Additive cardiac depression with other antiarrhythmics"],
    mnemonic: "\"Amides have 2 i's (li-do-caine); esters have 1. Add adrenaline to make it last.\"",
    vivaQuestions: [
      { q: "Why add adrenaline to lidocaine?", a: "Vasoconstriction slows absorption → longer action, less bleeding and lower systemic toxicity." },
      { q: "Why is an infected/acidic tissue harder to anaesthetise?", a: "Low pH keeps the drug ionised, reducing membrane penetration." },
    ],
    mcqs: [
      {
        id: "lido-m1",
        question: "Lidocaine produces anaesthesia by blocking:",
        options: ["K⁺ channels", "Na⁺ channels", "Ca²⁺ channels", "GABA receptors"],
        answerIndex: 1,
        explanation: "It blocks voltage-gated sodium channels in nerves.",
      },
      {
        id: "lido-m2",
        question: "Lidocaine as an antiarrhythmic belongs to class:",
        options: ["IA", "IB", "II", "III"],
        answerIndex: 1,
        explanation: "Lidocaine is a class IB antiarrhythmic.",
      },
    ],
  },

  // ── Antibiotics ──
  {
    id: "ceftriaxone",
    name: "Ceftriaxone",
    topic: "antibiotics",
    drugClass: "Third-generation cephalosporin (β-lactam)",
    moa: "Inhibits bacterial cell wall synthesis by binding penicillin-binding proteins.",
    uses: ["Meningitis", "Gonorrhoea", "Severe pneumonia / sepsis", "Typhoid fever"],
    sideEffects: ["Hypersensitivity", "Diarrhoea", "Biliary sludging (pseudolithiasis)", "Injection-site pain"],
    contraindications: ["Cephalosporin allergy", "Neonates with hyperbilirubinaemia", "Concurrent IV calcium in neonates"],
    interactions: ["Do not mix with calcium-containing IV fluids in neonates", "Cross-reactivity in penicillin allergy (~1–5%)"],
    mnemonic: "\"3rd-gen cephalosporins cross into CSF → good for meningitis.\"",
    vivaQuestions: [
      { q: "Why is ceftriaxone useful in meningitis?", a: "It achieves good penetration of the CSF and covers common pathogens." },
      { q: "Cephalosporin generation with best gram-negative & CNS cover?", a: "Third generation (e.g., ceftriaxone, cefotaxime)." },
    ],
    mcqs: [
      {
        id: "cef-m1",
        question: "Ceftriaxone is a:",
        options: ["Macrolide", "3rd-generation cephalosporin", "Aminoglycoside", "Fluoroquinolone"],
        answerIndex: 1,
        explanation: "It is a third-generation cephalosporin.",
      },
      {
        id: "cef-m2",
        question: "Ceftriaxone should not be co-administered with IV calcium in:",
        options: ["Elderly", "Neonates", "Pregnant women", "Diabetics"],
        answerIndex: 1,
        explanation: "Calcium–ceftriaxone precipitates can be fatal in neonates.",
      },
    ],
  },
  {
    id: "doxycycline",
    name: "Doxycycline",
    topic: "antibiotics",
    drugClass: "Tetracycline",
    moa: "Binds 30S ribosomal subunit → blocks aminoacyl-tRNA binding → inhibits protein synthesis (bacteriostatic).",
    uses: ["Atypical pneumonia", "Chlamydia", "Rickettsia / typhus", "Acne", "Malaria prophylaxis", "Cholera"],
    sideEffects: ["Photosensitivity", "Tooth discolouration & bone deposition", "GI upset", "Oesophageal ulceration"],
    contraindications: ["Pregnancy & lactation", "Children < 8 years"],
    interactions: ["Antacids / dairy / iron chelate it → ↓ absorption", "Enzyme inducers ↓ levels"],
    mnemonic: "\"Tetracyclines stain Teeth & harm the young — avoid < 8 yrs and in pregnancy.\"",
    vivaQuestions: [
      { q: "Why are tetracyclines avoided in children and pregnancy?", a: "They chelate calcium in developing teeth and bone → discolouration and growth inhibition." },
      { q: "Which subunit do tetracyclines bind?", a: "The 30S ribosomal subunit." },
    ],
    mcqs: [
      {
        id: "dox-m1",
        question: "Doxycycline should be avoided in:",
        options: ["Adults with pneumonia", "Children under 8 and pregnancy", "Acne", "Malaria prophylaxis"],
        answerIndex: 1,
        explanation: "It causes permanent tooth staining and affects bone growth.",
      },
      {
        id: "dox-m2",
        question: "Absorption of doxycycline is reduced by:",
        options: ["Vitamin C", "Milk and antacids", "Fatty meals", "Water"],
        answerIndex: 1,
        explanation: "Divalent cations (Ca, Mg, Fe) chelate tetracyclines.",
      },
    ],
  },
  {
    id: "vancomycin",
    name: "Vancomycin",
    topic: "antibiotics",
    drugClass: "Glycopeptide",
    moa: "Binds D-Ala-D-Ala terminus of peptidoglycan precursors → inhibits cell wall synthesis.",
    uses: ["MRSA infections", "Serious gram-positive infections", "Oral: C. difficile colitis"],
    sideEffects: ["Nephrotoxicity", "Ototoxicity", "\"Red man syndrome\" (rapid infusion)", "Thrombophlebitis"],
    contraindications: ["Previous severe hypersensitivity", "Caution in renal impairment"],
    interactions: ["Aminoglycosides → ↑ nephro/ototoxicity", "Infuse slowly to avoid red man syndrome"],
    mnemonic: "\"Vancomycin for MRSA & C. diff. Infuse slowly → avoid Red Man.\"",
    vivaQuestions: [
      { q: "What is red man syndrome?", a: "A histamine-release reaction (flushing of face/neck) from too-rapid vancomycin infusion — slow the infusion." },
      { q: "Oral vancomycin is used for?", a: "Severe Clostridioides difficile colitis (it is not absorbed, acting locally in the gut)." },
    ],
    mcqs: [
      {
        id: "van-m1",
        question: "Vancomycin is the drug of choice for:",
        options: ["Gram-negative sepsis", "MRSA", "Tuberculosis", "Malaria"],
        answerIndex: 1,
        explanation: "Vancomycin covers MRSA and serious gram-positive infections.",
      },
      {
        id: "van-m2",
        question: "Rapid infusion of vancomycin causes:",
        options: ["Gray baby syndrome", "Red man syndrome", "Serotonin syndrome", "Reye's syndrome"],
        answerIndex: 1,
        explanation: "Histamine release causes flushing — 'red man syndrome'.",
      },
    ],
  },
  {
    id: "benzylpenicillin",
    name: "Benzylpenicillin (Penicillin G)",
    topic: "antibiotics",
    drugClass: "Natural penicillin (β-lactam)",
    moa: "Binds penicillin-binding proteins and blocks cross-linking of the peptidoglycan cell wall, giving a bactericidal effect on dividing bacteria.",
    uses: ["Streptococcal infections", "Syphilis", "Meningococcal disease", "Rheumatic fever prophylaxis (benzathine)", "Gas gangrene"],
    sideEffects: ["Hypersensitivity / anaphylaxis", "Rash", "Jarisch-Herxheimer reaction in syphilis", "Seizures at very high doses"],
    contraindications: ["Penicillin hypersensitivity"],
    interactions: ["Probenecid raises levels by blocking renal tubular secretion", "May reduce efficacy of oral contraceptives"],
    mnemonic: "\"Penicillin G — Given by injection (acid-labile), Gram-positive cover, Gone quickly.\"",
    vivaQuestions: [
      { q: "Drug of choice for syphilis?", a: "Benzylpenicillin — long-acting benzathine penicillin." },
      { q: "Why can benzylpenicillin not be given orally?", a: "It is acid-labile and destroyed by gastric acid." },
    ],
    mcqs: [
      {
        id: "benzpen-m1",
        question: "Penicillins are bactericidal because they inhibit:",
        options: ["Protein synthesis", "Cell-wall synthesis", "DNA gyrase", "Folate synthesis"],
        answerIndex: 1,
        explanation: "β-lactams block peptidoglycan cross-linking in the bacterial cell wall.",
      },
      {
        id: "benzpen-m2",
        question: "Probenecid raises penicillin levels by:",
        options: ["Enhancing absorption", "Blocking renal tubular secretion", "Inhibiting liver metabolism", "Displacing protein binding"],
        answerIndex: 1,
        explanation: "Probenecid competes for the renal organic-acid transporter, slowing penicillin excretion.",
      },
    ],
  },
  {
    id: "amoxicillin-clavulanate",
    name: "Amoxicillin–Clavulanate (Co-amoxiclav)",
    topic: "antibiotics",
    drugClass: "Aminopenicillin + β-lactamase inhibitor",
    moa: "Amoxicillin inhibits cell-wall synthesis while clavulanic acid irreversibly inhibits β-lactamase, protecting amoxicillin and extending its spectrum.",
    uses: ["Otitis media", "Sinusitis", "Lower respiratory infections", "Animal and human bites", "Urinary tract infection"],
    sideEffects: ["Diarrhea (clavulanate)", "Rash", "Cholestatic hepatotoxicity (uncommon)", "Hypersensitivity"],
    contraindications: ["Penicillin hypersensitivity", "Previous co-amoxiclav-associated jaundice"],
    interactions: ["Probenecid raises amoxicillin levels", "Allopurinol increases rash risk"],
    mnemonic: "\"Clavulanate 'clavs' open the β-lactamase lock so amoxicillin can work.\"",
    vivaQuestions: [
      { q: "What is the role of clavulanic acid?", a: "It is a β-lactamase inhibitor that protects amoxicillin from enzymatic breakdown." },
      { q: "Why does co-amoxiclav cause more diarrhea than plain amoxicillin?", a: "The clavulanate component." },
    ],
    mcqs: [
      {
        id: "coamox-m1",
        question: "Clavulanic acid is combined with amoxicillin to:",
        options: ["Increase absorption", "Inhibit β-lactamase", "Prolong the half-life", "Reduce allergy risk"],
        answerIndex: 1,
        explanation: "Clavulanate inactivates β-lactamase, protecting amoxicillin.",
      },
    ],
  },
  {
    id: "piperacillin-tazobactam",
    name: "Piperacillin–Tazobactam",
    topic: "antibiotics",
    drugClass: "Antipseudomonal penicillin + β-lactamase inhibitor",
    moa: "Piperacillin inhibits cell-wall synthesis with broad Gram-negative cover including Pseudomonas; tazobactam inhibits β-lactamase to preserve activity.",
    uses: ["Hospital-acquired infections", "Febrile neutropenia", "Intra-abdominal sepsis", "Pseudomonas infections"],
    sideEffects: ["Diarrhea", "Hypersensitivity", "Hypokalemia", "Thrombocytopenia"],
    contraindications: ["Penicillin hypersensitivity"],
    interactions: ["Additive nephrotoxicity with vancomycin", "Prolongs non-depolarizing neuromuscular blockade", "Probenecid raises levels"],
    mnemonic: "\"Pip-Tazo — Pseudomonas + broad cover for the sick, hospitalized patient.\"",
    vivaQuestions: [
      { q: "Why is piperacillin-tazobactam chosen in febrile neutropenia?", a: "It gives broad-spectrum cover including antipseudomonal activity." },
    ],
    mcqs: [
      {
        id: "piptazo-m1",
        question: "Piperacillin-tazobactam is particularly valued for activity against:",
        options: ["MRSA", "Pseudomonas aeruginosa", "Mycobacterium tuberculosis", "Anaerobes only"],
        answerIndex: 1,
        explanation: "Piperacillin has strong antipseudomonal cover.",
      },
    ],
  },
  {
    id: "cefepime",
    name: "Cefepime",
    topic: "antibiotics",
    drugClass: "Fourth-generation cephalosporin (β-lactam)",
    moa: "Inhibits cell-wall synthesis with broad Gram-positive and Gram-negative cover including Pseudomonas, and is stable against many β-lactamases.",
    uses: ["Nosocomial pneumonia", "Febrile neutropenia", "Complicated urinary tract infection", "Pseudomonas infections"],
    sideEffects: ["Hypersensitivity", "Neurotoxicity / encephalopathy (esp. in renal impairment)", "Diarrhea", "C. difficile colitis"],
    contraindications: ["Cephalosporin hypersensitivity", "Dose adjustment needed in renal impairment"],
    interactions: ["Additive nephrotoxicity with aminoglycosides"],
    mnemonic: "\"Cefepime — 4th-gen: covers Gram-positives AND Pseudomonas.\"",
    vivaQuestions: [
      { q: "What does 4th-generation cefepime add over 3rd-generation cephalosporins?", a: "Antipseudomonal activity while keeping good Gram-positive cover." },
      { q: "Neurological adverse effect of cefepime in renal failure?", a: "Encephalopathy (cefepime neurotoxicity)." },
    ],
    mcqs: [
      {
        id: "cefepime-m1",
        question: "Cefepime is a cephalosporin of which generation?",
        options: ["First", "Second", "Third", "Fourth"],
        answerIndex: 3,
        explanation: "Cefepime is a fourth-generation cephalosporin with antipseudomonal cover.",
      },
    ],
  },
  {
    id: "meropenem",
    name: "Meropenem",
    topic: "antibiotics",
    drugClass: "Carbapenem (β-lactam)",
    moa: "Inhibits cell-wall synthesis with an ultra-broad spectrum (Gram-positive, Gram-negative and anaerobes) and high stability to β-lactamases.",
    uses: ["Severe or multidrug-resistant infections", "Intra-abdominal sepsis", "Meningitis", "Febrile neutropenia"],
    sideEffects: ["Diarrhea", "Hypersensitivity", "Seizures (less than imipenem)", "C. difficile colitis"],
    contraindications: ["Carbapenem / β-lactam hypersensitivity"],
    interactions: ["Markedly lowers valproate levels (risking seizures)", "Probenecid raises levels"],
    mnemonic: "\"Meropenem — the 'big gun': broadest β-lactam, reserve for resistant bugs.\"",
    vivaQuestions: [
      { q: "Why is meropenem often preferred over imipenem?", a: "Lower seizure risk and no need for cilastatin." },
      { q: "Important interaction of carbapenems with valproate?", a: "They sharply reduce valproate levels, which can precipitate seizures." },
    ],
    mcqs: [
      {
        id: "mero-m1",
        question: "Carbapenems such as meropenem must be used cautiously with:",
        options: ["Warfarin", "Valproate", "Metformin", "Statins"],
        answerIndex: 1,
        explanation: "Carbapenems lower serum valproate, risking loss of seizure control.",
      },
      {
        id: "mero-m2",
        question: "Meropenem belongs to which class of antibiotics?",
        options: ["Glycopeptide", "Carbapenem", "Macrolide", "Aminoglycoside"],
        answerIndex: 1,
        explanation: "Meropenem is a carbapenem β-lactam.",
      },
    ],
  },
  {
    id: "clindamycin",
    name: "Clindamycin",
    topic: "antibiotics",
    drugClass: "Lincosamide (protein-synthesis inhibitor)",
    moa: "Binds the 50S ribosomal subunit and inhibits protein synthesis; active against Gram-positives and anaerobes, and suppresses toxin production.",
    uses: ["Anaerobic infections above the diaphragm", "Skin and soft-tissue infections", "Necrotizing fasciitis / toxic shock (toxin suppression)", "Dental infections"],
    sideEffects: ["Pseudomembranous colitis (C. difficile)", "Diarrhea", "Rash", "Metallic taste (uncommon)"],
    contraindications: ["Hypersensitivity", "Previous C. difficile colitis"],
    interactions: ["Additive neuromuscular blockade", "Antagonism with macrolides (shared 50S site)"],
    mnemonic: "\"Clindamycin — Classic Cause of C. difficile Colitis.\"",
    vivaQuestions: [
      { q: "Which antibiotic is most classically linked to pseudomembranous colitis?", a: "Clindamycin (C. difficile overgrowth)." },
      { q: "Why is clindamycin added in necrotizing fasciitis?", a: "It suppresses bacterial toxin (protein) production." },
    ],
    mcqs: [
      {
        id: "clinda-m1",
        question: "The antibiotic most classically associated with pseudomembranous colitis is:",
        options: ["Clindamycin", "Gentamicin", "Vancomycin", "Doxycycline"],
        answerIndex: 0,
        explanation: "Clindamycin is the classic trigger of C. difficile colitis.",
      },
      {
        id: "clinda-m2",
        question: "Clindamycin inhibits bacterial protein synthesis at the:",
        options: ["30S subunit", "50S subunit", "DNA gyrase", "Cell wall"],
        answerIndex: 1,
        explanation: "Lincosamides bind the 50S ribosomal subunit.",
      },
    ],
  },
  {
    id: "metronidazole",
    name: "Metronidazole",
    topic: "antibiotics",
    drugClass: "Nitroimidazole (antibacterial and antiprotozoal)",
    moa: "Reduced inside anaerobic organisms to reactive intermediates that fragment microbial DNA, giving a bactericidal effect against anaerobes and protozoa.",
    uses: ["Anaerobic infections below the diaphragm", "Clostridioides difficile colitis", "Amoebiasis", "Giardiasis", "Trichomoniasis", "Bacterial vaginosis", "H. pylori regimens"],
    sideEffects: ["Metallic taste", "Nausea", "Disulfiram-like reaction with alcohol", "Peripheral neuropathy (prolonged use)", "Dark urine"],
    contraindications: ["Alcohol intake", "First trimester of pregnancy (caution)", "Hypersensitivity"],
    interactions: ["Alcohol → disulfiram-like reaction", "Potentiates warfarin", "Raises lithium and phenytoin levels"],
    mnemonic: "\"Metronidazole — Metallic taste, no alcohol; kills anaerobes below the diaphragm.\"",
    vivaQuestions: [
      { q: "Why must alcohol be avoided on metronidazole?", a: "It inhibits aldehyde dehydrogenase, causing a disulfiram-like reaction (flushing, vomiting)." },
      { q: "Metronidazole covers anaerobes in which region?", a: "Below the diaphragm — abdominal and pelvic infections." },
    ],
    mcqs: [
      {
        id: "metro-m1",
        question: "A patient taking metronidazole must strictly avoid:",
        options: ["Dairy products", "Alcohol", "Citrus fruit", "Iron tablets"],
        answerIndex: 1,
        explanation: "Metronidazole with alcohol causes a disulfiram-like reaction.",
      },
      {
        id: "metro-m2",
        question: "Metronidazole is effective against:",
        options: ["Aerobic Gram-negative rods", "Anaerobes and protozoa", "Mycobacteria", "Fungi"],
        answerIndex: 1,
        explanation: "It targets anaerobic bacteria and protozoa.",
      },
    ],
  },
  {
    id: "linezolid",
    name: "Linezolid",
    topic: "antibiotics",
    drugClass: "Oxazolidinone (protein-synthesis inhibitor)",
    moa: "Binds the 23S rRNA of the 50S subunit and prevents formation of the initiation complex; bacteriostatic against Gram-positives including MRSA and VRE.",
    uses: ["MRSA infections", "Vancomycin-resistant enterococci (VRE)", "Gram-positive pneumonia", "Complicated skin infections"],
    sideEffects: ["Thrombocytopenia / myelosuppression (prolonged use)", "Peripheral and optic neuropathy", "Serotonin syndrome", "Lactic acidosis"],
    contraindications: ["Concurrent MAO inhibitors", "Caution with serotonergic drugs and uncontrolled hypertension"],
    interactions: ["SSRIs / MAOIs → serotonin syndrome (linezolid is a weak MAOI)", "Tyramine-rich foods → hypertension"],
    mnemonic: "\"Linezolid — Last-line for VRE/MRSA; watch platelets and serotonin syndrome.\"",
    vivaQuestions: [
      { q: "What is the main use of linezolid?", a: "Serious Gram-positive infections including MRSA and VRE." },
      { q: "Why can linezolid cause serotonin syndrome?", a: "It is a weak, non-selective MAO inhibitor." },
    ],
    mcqs: [
      {
        id: "line-m1",
        question: "Linezolid is especially useful against:",
        options: ["Pseudomonas", "VRE and MRSA", "Anaerobes", "Mycobacteria"],
        answerIndex: 1,
        explanation: "Linezolid is reserved for resistant Gram-positives such as MRSA and VRE.",
      },
      {
        id: "line-m2",
        question: "A serious adverse effect of prolonged linezolid therapy is:",
        options: ["Nephrotoxicity", "Thrombocytopenia", "Ototoxicity", "Hepatitis"],
        answerIndex: 1,
        explanation: "Bone-marrow suppression, especially thrombocytopenia, occurs with prolonged use.",
      },
    ],
  },
  {
    id: "cotrimoxazole",
    name: "Cotrimoxazole (Trimethoprim–Sulfamethoxazole)",
    topic: "antibiotics",
    drugClass: "Folate-synthesis inhibitor combination (sulfonamide + trimethoprim)",
    moa: "Sulfamethoxazole blocks dihydropteroate synthase and trimethoprim blocks dihydrofolate reductase — sequential blockade of folate synthesis gives a synergistic bactericidal effect.",
    uses: ["Urinary tract infection", "Pneumocystis jirovecii pneumonia (treatment and prophylaxis)", "Toxoplasmosis", "Nocardiosis", "Some MRSA infections"],
    sideEffects: ["Hypersensitivity / Stevens-Johnson syndrome", "Hyperkalemia", "Megaloblastic anemia", "Crystalluria", "Kernicterus in neonates"],
    contraindications: ["Pregnancy near term and neonates", "Sulfa allergy", "Severe renal impairment", "G6PD deficiency"],
    interactions: ["Potentiates warfarin", "Raises methotrexate toxicity", "Hyperkalemia with ACE inhibitors/ARBs/spironolactone"],
    mnemonic: "\"Cotrimoxazole — double folate block; drug of choice for PCP.\"",
    vivaQuestions: [
      { q: "Drug of choice for Pneumocystis jirovecii pneumonia?", a: "Cotrimoxazole." },
      { q: "Why is the combination synergistic?", a: "It blocks two sequential steps of bacterial folate synthesis." },
    ],
    mcqs: [
      {
        id: "cotrim-m1",
        question: "Cotrimoxazole is the drug of choice for:",
        options: ["Tuberculosis", "Pneumocystis jirovecii pneumonia", "Malaria", "Candidiasis"],
        answerIndex: 1,
        explanation: "Cotrimoxazole is first-line for Pneumocystis jirovecii pneumonia.",
      },
      {
        id: "cotrim-m2",
        question: "Cotrimoxazole works by inhibiting:",
        options: ["Cell-wall synthesis", "Sequential folate synthesis", "DNA gyrase", "Protein synthesis"],
        answerIndex: 1,
        explanation: "It blocks two steps in the folate pathway (dihydropteroate synthase and dihydrofolate reductase).",
      },
    ],
  },

  // ── Antimicrobials (Anti-TB) ──
  {
    id: "rifampicin",
    name: "Rifampicin",
    topic: "antimicrobials",
    drugClass: "Antitubercular (first-line)",
    moa: "Inhibits bacterial DNA-dependent RNA polymerase → blocks RNA synthesis.",
    uses: ["Tuberculosis (with isoniazid, pyrazinamide, ethambutol)", "Leprosy", "Meningococcal prophylaxis"],
    sideEffects: ["Orange-red urine/tears/sweat", "Hepatotoxicity", "Flu-like syndrome", "Potent enzyme induction"],
    contraindications: ["Active hepatic disease", "Caution with many co-medications"],
    interactions: ["Potent CYP450 inducer → ↓ OCPs, warfarin, protease inhibitors, many drugs"],
    mnemonic: "\"Rifampicin turns secretions Red-orange and Revs up (induces) liver enzymes.\"",
    vivaQuestions: [
      { q: "Harmless but alarming side effect of rifampicin?", a: "Orange-red discolouration of urine, sweat and tears." },
      { q: "Why can rifampicin cause oral contraceptive failure?", a: "It is a potent hepatic enzyme inducer that increases oestrogen/progesterone metabolism." },
    ],
    mcqs: [
      {
        id: "rif-m1",
        question: "Rifampicin inhibits:",
        options: ["Cell wall synthesis", "DNA-dependent RNA polymerase", "30S ribosome", "Folate synthesis"],
        answerIndex: 1,
        explanation: "It blocks bacterial RNA polymerase.",
      },
      {
        id: "rif-m2",
        question: "Rifampicin characteristically causes:",
        options: ["Blue urine", "Orange-red body secretions", "Green sweat", "Black tears"],
        answerIndex: 1,
        explanation: "Rifampicin colours urine, sweat and tears orange-red.",
      },
    ],
  },

  // ── Endocrine ──
  {
    id: "levothyroxine",
    name: "Levothyroxine (T4)",
    topic: "endocrine-pharmacology",
    drugClass: "Thyroid hormone (synthetic T4)",
    moa: "Synthetic thyroxine converted to active T3, restoring normal metabolic rate.",
    uses: ["Hypothyroidism", "Myxoedema", "Thyroid hormone replacement after thyroidectomy"],
    sideEffects: ["Palpitations / tachycardia (over-dose)", "Weight loss", "Tremor", "Osteoporosis with over-treatment", "Angina in the elderly"],
    contraindications: ["Untreated adrenal insufficiency", "Recent MI (start low)"],
    interactions: ["Iron, calcium, antacids ↓ absorption", "Increases warfarin effect"],
    mnemonic: "\"Levo = Low thyroid replacement. Take on an empty stomach, monitor TSH.\"",
    vivaQuestions: [
      { q: "How is levothyroxine dose monitored?", a: "By measuring serum TSH (aim to normalise it)." },
      { q: "Why start low in elderly/cardiac patients?", a: "Sudden full replacement can precipitate angina or arrhythmia." },
    ],
    mcqs: [
      {
        id: "lev-m1",
        question: "Levothyroxine therapy is monitored by:",
        options: ["Serum T4 only", "Serum TSH", "Free calcium", "Serum cortisol"],
        answerIndex: 1,
        explanation: "TSH is the best marker of adequate replacement.",
      },
      {
        id: "lev-m2",
        question: "Levothyroxine absorption is reduced by:",
        options: ["Empty stomach", "Iron and calcium supplements", "Water", "Morning dosing"],
        answerIndex: 1,
        explanation: "Iron/calcium/antacids bind levothyroxine and reduce absorption.",
      },
    ],
  },
  {
    id: "prednisolone",
    name: "Prednisolone",
    topic: "endocrine-pharmacology",
    drugClass: "Glucocorticoid (corticosteroid)",
    moa: "Binds glucocorticoid receptors → ↓ phospholipase A2 & inflammatory gene transcription → anti-inflammatory & immunosuppressant.",
    uses: ["Asthma / COPD exacerbation", "Autoimmune & allergic disease", "Anaphylaxis (adjunct)", "Immunosuppression", "Nephrotic syndrome"],
    sideEffects: ["Cushingoid features", "Hyperglycaemia", "Osteoporosis", "Peptic ulcer", "Immunosuppression / infection", "Adrenal suppression"],
    contraindications: ["Systemic fungal infection", "Live vaccines", "Caution in diabetes, peptic ulcer"],
    interactions: ["NSAIDs → ↑ GI bleeding", "Raises glucose (antagonises antidiabetics)", "Enzyme inducers ↓ levels"],
    mnemonic: "\"Steroid SEs — CUSHINGOID. Never stop abruptly → taper (adrenal suppression).\"",
    vivaQuestions: [
      { q: "Why must long-term steroids be tapered, not stopped?", a: "Chronic use suppresses the HPA axis; abrupt withdrawal causes an adrenal (Addisonian) crisis." },
      { q: "Name three major adverse effects of glucocorticoids.", a: "Osteoporosis, hyperglycaemia, immunosuppression (also peptic ulcer, Cushingoid habitus, hypertension)." },
    ],
    mcqs: [
      {
        id: "pred-m1",
        question: "Prednisolone's anti-inflammatory action involves inhibiting:",
        options: ["Cyclo-oxygenase directly", "Phospholipase A2", "Lipoxygenase only", "Thromboxane synthase"],
        answerIndex: 1,
        explanation: "Steroids induce annexin-1, inhibiting phospholipase A2.",
      },
      {
        id: "pred-m2",
        question: "Long-term corticosteroids should be withdrawn by:",
        options: ["Stopping abruptly", "Gradual tapering", "Alternate high doses", "Doubling then stopping"],
        answerIndex: 1,
        explanation: "Tapering avoids adrenal insufficiency from HPA suppression.",
      },
    ],
  },

  // ── NSAIDs & analgesics ──
  {
    id: "paracetamol",
    name: "Paracetamol (Acetaminophen)",
    topic: "nsaids-analgesics",
    drugClass: "Analgesic / antipyretic (weak COX inhibitor, central)",
    moa: "Inhibits central prostaglandin synthesis; minimal peripheral anti-inflammatory action.",
    uses: ["Fever", "Mild–moderate pain", "Safe analgesic in children & pregnancy"],
    sideEffects: ["Generally well tolerated", "Hepatotoxicity in overdose", "Rare skin reactions"],
    contraindications: ["Severe hepatic impairment", "Caution with chronic alcohol use"],
    interactions: ["Chronic alcohol / enzyme inducers ↑ hepatotoxicity risk"],
    mnemonic: "\"Paracetamol: no gastric/antiplatelet effect. Overdose antidote = N-acetylcysteine.\"",
    vivaQuestions: [
      { q: "Antidote for paracetamol overdose?", a: "N-acetylcysteine (replenishes glutathione)." },
      { q: "Why is paracetamol preferred over aspirin in children?", a: "No risk of Reye's syndrome; no gastric irritation or antiplatelet effect." },
    ],
    mcqs: [
      {
        id: "para-m1",
        question: "The antidote for paracetamol poisoning is:",
        options: ["Naloxone", "N-acetylcysteine", "Flumazenil", "Atropine"],
        answerIndex: 1,
        explanation: "N-acetylcysteine restores hepatic glutathione.",
      },
      {
        id: "para-m2",
        question: "Compared with aspirin, paracetamol lacks:",
        options: ["Antipyretic action", "Analgesic action", "Anti-inflammatory & antiplatelet action", "Oral absorption"],
        answerIndex: 2,
        explanation: "Paracetamol has little peripheral anti-inflammatory or antiplatelet effect.",
      },
    ],
  },
  {
    id: "ibuprofen",
    name: "Ibuprofen",
    topic: "nsaids-analgesics",
    drugClass: "NSAID (reversible non-selective COX inhibitor)",
    moa: "Reversibly inhibits COX-1 & COX-2 → ↓ prostaglandins.",
    uses: ["Pain", "Fever", "Inflammation / arthritis", "Dysmenorrhoea"],
    sideEffects: ["Gastric irritation / ulcer", "Renal impairment", "Fluid retention / raised BP", "Bronchospasm in sensitive asthmatics"],
    contraindications: ["Active peptic ulcer", "Severe renal impairment", "Third-trimester pregnancy", "Aspirin-sensitive asthma"],
    interactions: ["↓ antihypertensive effect of ACE inhibitors/diuretics", "↑ bleeding with anticoagulants", "Antagonises aspirin's antiplatelet action"],
    mnemonic: "\"NSAIDs hit the Stomach, Kidney and Platelets — reversible (unlike aspirin).\"",
    vivaQuestions: [
      { q: "How does ibuprofen differ from aspirin mechanistically?", a: "Ibuprofen inhibits COX reversibly; aspirin does so irreversibly." },
      { q: "Why do NSAIDs cause peptic ulcers?", a: "Loss of protective gastric prostaglandins (COX-1 inhibition) reduces mucus/bicarbonate." },
    ],
    mcqs: [
      {
        id: "ibu-m1",
        question: "Ibuprofen inhibits cyclo-oxygenase:",
        options: ["Irreversibly", "Reversibly", "Only COX-2", "Not at all"],
        answerIndex: 1,
        explanation: "Unlike aspirin, ibuprofen is a reversible COX inhibitor.",
      },
      {
        id: "ibu-m2",
        question: "A common adverse effect of NSAIDs like ibuprofen:",
        options: ["Peptic ulceration", "Hypoglycaemia", "Bradycardia", "Hair loss"],
        answerIndex: 0,
        explanation: "Reduced gastric prostaglandins cause mucosal damage.",
      },
    ],
  },
];

// Drugs flagged high-yield for Russian MBBS pharmacology exams. Kept as ID sets
// so the tag can be applied in one place (and overridden per-drug via JSON).
const IMPORTANT_FOR_EXAM = new Set<string>([
  "atropine", "adrenaline", "noradrenaline", "neostigmine", "propranolol", "salbutamol",
  "metoprolol", "atenolol", "losartan", "enalapril", "amlodipine", "furosemide",
  "hydrochlorothiazide", "nitroglycerin", "digoxin", "diazepam", "morphine", "phenytoin",
  "haloperidol", "lidocaine", "amoxicillin", "ceftriaxone", "azithromycin", "gentamicin",
  "ciprofloxacin", "doxycycline", "vancomycin", "isoniazid", "rifampicin", "insulin",
  "metformin", "levothyroxine", "prednisolone", "paracetamol", "aspirin", "ibuprofen",
  "cetirizine", "diphenhydramine", "promethazine", "cyproheptadine", "ondansetron",
  "sumatriptan", "misoprostol", "latanoprost",
  "benzylpenicillin", "amoxicillin-clavulanate", "piperacillin-tazobactam", "cefepime",
  "meropenem", "clindamycin", "metronidazole", "linezolid", "cotrimoxazole",
]);

const ASKED_FREQUENTLY = new Set<string>([
  "atropine", "adrenaline", "propranolol", "metoprolol", "furosemide", "enalapril",
  "digoxin", "diazepam", "morphine", "phenytoin", "amoxicillin", "gentamicin",
  "isoniazid", "rifampicin", "insulin", "metformin", "aspirin", "paracetamol",
  "diphenhydramine", "ondansetron", "sumatriptan", "misoprostol",
  "benzylpenicillin", "meropenem", "clindamycin", "metronidazole", "cotrimoxazole",
]);

// Final drug list = core drugs + any JSON/CSV imports, with exam tags applied.
// Import path: drop objects into data/drugs.json (see data/README.md).
export const DRUGS: Drug[] = [...CORE_DRUGS, ...(extraDrugs as Drug[])].map((d) => ({
  ...d,
  importantForExam: d.importantForExam ?? IMPORTANT_FOR_EXAM.has(d.id),
  askedFrequently: d.askedFrequently ?? ASKED_FREQUENTLY.has(d.id),
}));

// Fail fast on duplicate drug IDs. getDrug() and the /drug/[id] route rely on
// find(), which silently returns only the first match — a duplicate id would
// hide a drug and double it in flashcards/MCQs. This throws at module load
// (build + dev), so mistakes surface immediately rather than shipping.
(function assertUniqueDrugIds(list: Drug[]) {
  const seen = new Set<string>();
  const dups = new Set<string>();
  for (const d of list) {
    if (seen.has(d.id)) dups.add(d.id);
    seen.add(d.id);
  }
  if (dups.size) {
    throw new Error(`Duplicate drug id(s) in drug data: ${[...dups].join(", ")}`);
  }
})(DRUGS);

export function getDrug(id: string): Drug | undefined {
  return DRUGS.find((d) => d.id === id);
}

export function getDrugsByTopic(topic: string): Drug[] {
  return DRUGS.filter((d) => d.topic === topic);
}

export function getImportantDrugs(): Drug[] {
  return DRUGS.filter((d) => d.importantForExam);
}

export function getFrequentDrugs(): Drug[] {
  return DRUGS.filter((d) => d.askedFrequently);
}
